### ISSUE TITLE
Package tests test_dwarfdumpPE.sh and test_dwarfdumpMacos.sh failing

### ISSUE THREAD

**Issue by sindhu-karri** [davea42/libdwarf-code#212] opened 2023-12-15 09:42 UTC
The tests  test_dwarfdumpPE.sh and test_dwarfdumpMacos.sh are failing with an error that libdwarf.so.0 could not be found.
The libdwarf.so.0 is generated by make. But it still cannot be found.
This error is resolved when the libdwarf.so.0 is copied to /usr/lib64

This happens when the libdwarf package is tested without installation.

time="2023-12-15T05:54:45Z" level=debug msg="PASS: test_canonical"
time="2023-12-15T05:54:45Z" level=debug msg="PASS: test_dwarflebtest"
time="2023-12-15T05:54:45Z" level=debug msg="PASS: test_dwarfstring"
time="2023-12-15T05:54:45Z" level=debug msg="PASS: test_dwgetopt"
time="2023-12-15T05:54:45Z" level=debug msg="PASS: test_errmsglist"
time="2023-12-15T05:54:45Z" level=debug msg="PASS: test_extra_flag_strings"
time="2023-12-15T05:54:45Z" level=debug msg="PASS: test_getnametest"
time="2023-12-15T05:54:45Z" level=debug msg="PASS: test_helpertree"
time="2023-12-15T05:54:45Z" level=debug msg="PASS: test_ignoresec"
time="2023-12-15T05:54:45Z" level=debug msg="PASS: test_int64_test"
time="2023-12-15T05:54:45Z" level=debug msg="PASS: test_linkedtopath"
time="2023-12-15T05:54:45Z" level=debug msg="PASS: test_macrocheck"
time="2023-12-15T05:54:45Z" level=debug msg="PASS: test_makenametest"
time="2023-12-15T05:54:45Z" level=debug msg="PASS: test_regex"
time="2023-12-15T05:54:45Z" level=debug msg="PASS: test_safe_strcpy"
time="2023-12-15T05:54:45Z" level=debug msg="PASS: test_setupsections"
time="2023-12-15T05:54:45Z" level=debug msg="PASS: test_testesb"
time="2023-12-15T05:54:45Z" level=debug msg="PASS: test_sanitized"
time="2023-12-15T05:54:45Z" level=debug msg="PASS: test_tied"
time="2023-12-15T05:54:45Z" level=debug msg="PASS: test_dwarfdumpLinux.sh"
time="2023-12-15T05:54:45Z" level=debug msg="FAIL: test_dwarfdumpPE.sh"
time="2023-12-15T05:54:45Z" level=debug msg="FAIL: test_dwarfdumpMacos.sh"
time="2023-12-15T05:54:45Z" level=debug msg="============================================================================"
time="2023-12-15T05:54:45Z" level=debug msg="Testsuite summary for libdwarf 0.9.0"
time="2023-12-15T05:54:45Z" level=debug msg="============================================================================"
time="2023-12-15T05:54:45Z" level=debug msg="# TOTAL: 22"
time="2023-12-15T05:54:45Z" level=debug msg="# PASS:  20"
time="2023-12-15T05:54:45Z" level=debug msg="# SKIP:  0"
time="2023-12-15T05:54:45Z" level=debug msg="# XFAIL: 0"
time="2023-12-15T05:54:45Z" level=debug msg="# FAIL:  2"
time="2023-12-15T05:54:45Z" level=debug msg="# XPASS: 0"
time="2023-12-15T05:54:45Z" level=debug msg="# ERROR: 0"
time="2023-12-15T05:54:45Z" level=debug msg="============================================================================"
time="2023-12-15T05:54:45Z" level=debug msg="See test/test-suite.log"

------------------------------------------------------------------------------------------------------------------------------
   libdwarf 0.9.0: test/test-suite.log
=========================================

# TOTAL: 22
# PASS:  20
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test_dwarfdumpPE.sh
=========================

TOP topsrc .. topbld /root/rpmbuild/SOURCES/libdwarf-0.9.0/test/.. localsrc ../test
start  test_dwarfdumpPE.sh sanity check on pe ../test/testobjLE32PE.exe
**Run: /root/rpmbuild/SOURCES/libdwarf-0.9.0/test/../src/bin/dwarfdump/dwarfdump -vvv -a  ../test/testobjLE32PE.exe | head -n 700
/root/rpmbuild/SOURCES/libdwarf-0.9.0/src/bin/dwarfdump/.libs/lt-dwarfdump: error while loading shared libraries: libdwarf.so.0: cannot open shared object file: No such file or directory**
if update required, mv /root/rpmbuild/SOURCES/libdwarf-0.9.0/test/../test/junk.testobjLE32PE.base ../test/testobjLE32PE.base
Fix Last Time to 0, mv /root/rpmbuild/SOURCES/libdwarf-0.9.0/test/../test/junk2.testobjLE32PE.base /root/rpmbuild/SOURCES/libdwarf-0.9.0/test/../test/junk.testobjLE32PE.base
.............
FAIL: test_dwarfdumpMacos.sh
============================

TOP topsrc .. topbld /root/rpmbuild/SOURCES/libdwarf-0.9.0/test/.. localsrc ../test
start dwarfdumpMacos.sh dwarfdump sanity check on ../test/test-mach-o-32.dSYM
Run: /root/rpmbuild/SOURCES/libdwarf-0.9.0/test/../src/bin/dwarfdump/dwarfdump -a -vvv  ../test/test-mach-o-32.dSYM | head -n 700
**/root/rpmbuild/SOURCES/libdwarf-0.9.0/src/bin/dwarfdump/.libs/lt-dwarfdump: error while loading shared libraries: libdwarf.so.0: cannot open shared object file: No such file or directory**
report file lengths
  700 ../test/test-mach-o-32.base
    0 /root/rpmbuild/SOURCES/libdwarf-0.9.0/test/../test/junk.test-mach-o-32.base
  700 total
if update required, mv /root/rpmbuild/SOURCES/libdwarf-0.9.0/test/../test/junk.test-mach-o-32.base ../test/test-mach-o-32.base
Fix Last Time to 0, mv /root/rpmbuild/SOURCES/libdwarf-0.9.0/test/../test/junk2.test-mach-o-32.base /root/rpmbuild/SOURCES/libdwarf-0.9.0/test/../test/junk.test-mach-o-32.base
..................

find / -name libdwarf.so.0
/root/rpmbuild/SOURCES/libdwarf-0.9.0/src/lib/libdwarf/.libs/libdwarf.so.0
/root/BUILDROOT/libdwarf-0.9.0-1.cm2.x86_64/usr/lib/libdwarf.so.0

**Comment by davea42** [comment] 2023-12-15 19:35
If you  look at scripts/allsimplebuilds.sh you will notice that the scripts all do a make install
(but not to the system directories).   That is essential to avoid the fail when building
libdwarf.so shared library. It seems surprising that this works, but... it does.
.
You can select any directory to install to, there is no need to install in system locations
for the tests to work.

Yes, it's a little odd. But easy to do.  I'm adding a short section on this
in the libdwarf documentation (doc/libdwarf.dox) today.

**Comment by davea42** [comment] 2023-12-16 16:50
Did my comment help at all?   Is this issue resolved?

**Comment by davea42** [comment] 2023-12-18 20:55
I'm going to assume the issue is resolved. Closing.

**Closed by davea42** 2023-12-18 20:55 UTC
