### ISSUE TITLE
Directory name added twice to file name in dwarf_srcfiles

### ISSUE THREAD

**Issue by pedronavf** [davea42/libdwarf-code#181] opened 2023-08-10 08:30 UTC
Attached is glibc 2.35's debug file from Ubuntu 22.04.01

[69389d485a9793dbe873f0ea2c93e02efaa9aa3d.zip](https://github.com/davea42/libdwarf-code/files/12310353/69389d485a9793dbe873f0ea2c93e02efaa9aa3d.zip)

When calling `dwarf_srcfiles`  if the DIE has a `DW_AT_name` with just a flie name, then `DW_AT_comp_dir` gets added twice to the file name. If `DW_AT_comp_dir` has a relative path, the file name returned is correct.

Example:
Correct:
```
DIE offset: 0x1776ab
DW_AT_name: ../sysdeps/unix/sysv/linux/libc_fatal.c
DW_AT_comp_dir: ./libio
```
`dwarf_srcfiles` returns `./libio/../sysdeps/posix/libc_fatal.c` which is correct.

Wrong:
```
DIE offset: 0x202592
DW_AT_name: pthread_kill.c
DW_AT_comp_dir: ./ntpl
```
`dwarf_srcfiles` returns `./nptl/./nptl/pthread_kill.c` instead of `./ntpl/pthread_kill.c`

**Comment by davea42** [comment] 2023-08-10 15:51
The problem is in create_fullest_file_path() (libdwarf) and is a failure to correctly deal
with DWARF5 (the algorithm there needs a small addition to treat < 5 one way
and >= 5 another way in dealing with line table header data).

**Comment by davea42** [comment] 2023-08-11 16:58
I have the correct fix and am doing full testing. I hope to push the fix today.

**Comment by davea42** [comment] 2023-08-17 20:44
See the ChangeLog for details on the specific situation libdwarf was not
working right.  It is fixed and tested and the fix pushed 12 August 2023
to github, so I am closing this report.

**Closed by davea42** 2023-08-17 20:44 UTC
