### ISSUE TITLE
tests under Valgrind 

### ISSUE THREAD

**Issue by hnarkaytis** [davea42/libdwarf-code#133] opened 2022-08-31 20:36 UTC
I would recommend to add special target for tests under Valgrind. It will help to detect memory leaks and improper memory access earlier.

Sample integration [here](https://github.com/alexanderchuranov/Metaresc/blob/master/tests/Makefile.am#L76)

**Comment by hnarkaytis** [comment] 2022-09-01 01:50
I double checked dwarfdump with valgrind on some random object file. Indeed it leaves zero unallocated memory. I guess that it require automated valgrind check in the CI. Also it make sense to look into Python [hyposis](https://hypothesis.readthedocs.io/en/latest/) to iterate over combinations of command line arguments and ensure that dwaftdump exits clean with any combination of them.

For the library it still make sense to do valgrind checks to ensure that correct usage from the test do not leave unallocated memory blocks. For example dwarf_attrlist allocates memory for the list of attributes and string attributes. This memory should be deallocated by dwarf_dealloc. How you could ensure that all strings are correctly deallocated? You either need to make a unit test for every tag type and custom allocator/deallocator, or just one test that will have a collection of attributes of all types and run it under valgrind. Custom allocators/deallocators will work for unit test and ensure that all memory deallocated correctly, but it will not give any guarantee that library do not read or use any uninitialised memory. It means that in unit tests code is always successful, because initial state is good enough for correct outcomes, but in user environment it will fail miserable because of usage of uninitialised memory. Valgrind closes this gap.

Here is another test methodology that require valgrind. You need to have a test to ensure that library works correctly (at least do not crash or leave unallocated blocks) in case if system runs out of memory. You need to replace standard memory allocator on a custom one, that will return NULL after specific number of allocations. First you set this number to zero and make a library call that suppose to do memory allocation. Expected behaviour - library call should report an error. Next - you increment the number and to the call again. If call makes more than one allocation it will fail again. So you repeat this until library call will get under threshold of allocation. Finally you need to check that all failed calls freed memory that they allocated.

This approach could also be extended to a little bit smarter brute force. Custom allocator should store a set of stack traces (see man 3 backtrace) that made a call to memory allocator. If stack trace is not in the set (allocator was called for the first time from the specific execution flow) then allocator return NULL and store this stack trace into the set. On the next attempt from the same execution flow it will return allocated block. Outer loop iterates the call until it fails.

**Comment by davea42** [comment] 2022-09-01 15:52
Much of what you describe (you describe a lot of things, so I'll have to think about this) is already handled in the regressiontests.  All the dwarfdump options and many combinations of them are run (not all combinations, of course,
there being well over 100 options).  A feature of libdwarf is that it cleans up at dwarf_finish().  And there is the option to say to the library 'do not clean up' (done to show that dwarfdump is dealloc-ing as soon as possible and thoroughly but no sooner, avoiding memory bloat, as this is when -fsanitize is in use ).  The regression tests are all run both ways.    dwarfdump --suppress-de-alloc-tree (which I just realized
is not listed in dwarfdump -h. Oops. Fixing that oversight now.)

I have run with a special allocator at times, telling it to return NULL after n calls, but I admit I've not done that for a few years...oops.  There's always room for improvement.  I confess the existence of backtrace() is news to me!

Well. Several interesting ideas. Things I need to think about.
 Thanks.

**Comment by davea42** [comment] 2022-09-01 15:56
-fsanitize is pretty good at noting memory not free/dealloc.  I've not found valgrind
better at noting that sort of error.  But I'm not *sure* -fsanitize is as good
for that specific test as valgrind.

**Comment by hnarkaytis** [comment] 2022-09-01 16:34
The thing that -fsanitize will not find is the following scenario (what I call use of uninitialised memory):
Let's say you have a structure:
struct foo {
  char x;
  int y;
};
You need to calculate hash out of this structure and you have generic hash function that takes void * ptr and size_t size. The problem here that padding bytes in structure will also be hashed in this case.  It's not obvious and valgrind will give you a warning that hashing function reads the memory that was not initialised.
The other common case is a use on a long double. sizeof (long double) == 16, but it uses only 10 bytes. I.e. 6 bytes are not initialised.

WRT custom allocators and use of backtrace. It also make sense to detect recursion loops and exclude them from the trace. It might not be the case for libdwarf, but is useful in my case.

**Comment by davea42** [comment] 2022-09-03 15:15
I implemented use of valgrind running dwarfdump using
valgrind -q --leak-check=full
and there were no errors ( about 18000 individual tests).

Leaving off -q is hopeless, valgrind always writes
something without -q.

A run with no analysis   21 min
A run with -fsanitize       45 min
A run with valgrind         469 min

They all PASS as no run caused any unusual output.

So not a good idea to run valgrind when one wants a quick check!
But thanks for the idea, it is baked into libdwarf-regressiontests/DWARFTEST.sh
now for use as desired.

**Comment by davea42** [comment] 2022-09-04 02:19
With under 50 or so malloc allowed to work
and no object file on the dwarfdump command line one does get odd messages
and -fsanitize notes leaked memory.  This is *after* fixing some problems
where a failure failed to clear the 'makename' name tree.

Small stuff, but... not good.
Once this is cleared will look at actually naming an object file for dwarfdump!

**Comment by vtorri** [comment] 2022-09-04 07:17
> I implemented use of valgrind running dwarfdump using valgrind -q --leak-check=full and there were no errors ( about 18000 individual tests).
> 
> Leaving off -q is hopeless, valgrind always writes something without -q so comparing older dwarfdump output with leak-check would show differences ... everywhere..
> 
> A run with no analysis 21 min A run with -fsanitize 45 min A run with valgrind 469 min

then run valgrind just before a release (before going to sleep :-D)

be sure that there is no memory error at the end of the valgrind output

**Comment by davea42** [comment] 2022-09-05 17:00
Running dwarfdump  with an interceptor for malloc/calloc and
returning NULL after N calls to them (for a wide range of N)
showed that with no object file presented to dwarfdump there were 
lots of  things never freed.  

And for certain really-badly-corrupted target object files
dwarfdump had a little additional never-freed data.

With small  mods to dwarf_alloc.c, dwarf_error.c,
and a call added to dwarf_init_finish.c 
I think I have all this fixed. 

 It's going to take at -least- a day or two 
to verify  the local version  passes all the tests, including the new ones
for the valgrind and  malloc-exhaustion testing.

**Comment by hnarkaytis** [comment] 2022-09-06 22:36
Automated tests with Valgrind should use flags --leak-check=full --error-exitcode=1 --quiet
--error-exitcode=<non-zero exit code> - reports to tests runner that Valgrind detected memory error (without this flag exit code is a value from test program)

**Comment by davea42** [comment] 2022-09-07 00:08
--show-leak-kinds=all
seems good, it reveals malloc memory with a base in known data but
not freed.  

Thanks for the --error-exitcode=1

I discovered a major oversight in dd_esb.c exposed when after 200 calls
 to malloc it always returned 0.   Took hours to understand, but the fix was
not complicated or extensive.  

Much more confident now that we can get to zero leaks.
But it will be another couple days to redo all the testing.

**Comment by davea42** [comment] 2022-09-12 16:00
--error-exitcode=3 turns out to be kind of useless for dwarfdump.

From the online doc:
 ```
--error-exitcode=<number> [default: 0]

    Specifies an alternative exit code to return if Valgrind reported any errors in the run. When set to the default value (zero), the return value from Valgrind will always be the return value of the process being simulated. When set to a nonzero value, that value is returned instead, if Valgrind detects any errors. This is useful for using Valgrind as part of an automated test suite, since it makes it easy to detect test cases for which Valgrind has reported errors, just by inspecting return codes.
```

What that does not say is what code is returned if the application exits with a non-zero exit code.
In my testing it means that the non-zero returned by the application under test
is returned by valgrind. Incomplete documentation?

So if dwarfdump returns 1 valgrind returns 1 (assuming valgrind found no errors).
Am I misreading the 
https://valgrind.org/docs/manual/manual-core.html#manual-core.basicopts
???

**Comment by davea42** [comment] 2022-09-12 17:30
I sent a suggestion to the valgrind-users list suggesting a small addition  to
the web page wording on --error-exitcode=  to clarify the question I raised above.

**Comment by davea42** [comment] 2022-09-12 20:51
I filed a bug on this documentation issue on bugs.kde.org, after a valgrind-users sent me 
a private email as to where to file a bug report.

https://bugs.kde.org/show_bug.cgi?id=459031

**Comment by davea42** [comment] 2022-09-13 16:05
Neither -fsanitize nor valgrind find issues in running the 18000 regression tests.
Nor does valgrind find issues in running with a limit defining a max number
of malloc calls allowed to succeed (after that all such calls return NULL).
Run with the following  set of max successful alloc:
for x in 1 2 3 4 5 10 50 100 150 200 250 300 350  400 450 500 550 600 650 700 800 900 1000 5000 10000 15000 20000 100000 1000000 10000000
Neither libdwarf nor dwarfdump leak.
The tiny source and the runscripts for these tests is not on github, it's just
in a local directory here.

Since I now have a reproducible  test set I think it's time to close this issue.

**Closed by davea42** 2022-09-13 16:05 UTC
