### ISSUE TITLE
DWARF2 DW_FORM_ref_addr Support

### ISSUE THREAD

**Issue by TixoRebel** [davea42/libdwarf-code#215] opened 2024-01-07 21:21 UTC
I'm working with an old compiler which outputs DWARF2 debug info and as per a mistake in the original specifications it incorrectly uses DW_FORM_ref_addr in place of DW_FORM_addr. Would it be possible to re-add support for this case to libdwarf as it seems like it was [removed sometime in the past](https://github.com/davea42/libdwarf-code/blob/60c15ba27c5693193b4c9cd7ef02cca7a05693ed/src/lib/libdwarf/dwarf_form.c#L1279)? Unfortunately it was removed before the library made it to git so I'm not sure how to properly handle that case.

**Comment by davea42** [comment] 2024-01-07 23:20
The problem was specific to previous compilers.  

Other compilers emit correct DWARF. What would help most is
an object file showing the problem, as that  identifies the compiler too.
I do not believe I have ever had a testcase showing the problem, but perhaps I do?

This change was made to dwarf_form.c and dwarf_util.c around 2014-04-12,
in 0b74b138086610dcdff26e3bbded4c9e3aeb9b77 and
87f877b87dc369cc19d9f9232bf48885a548ac58 preceded the change.  I will take a look.
I will be away next week.

**Comment by davea42** [comment] 2024-01-07 23:28
Yes, looking at the change, 
case DW_FORM_ref_addr:
+        {
+            /*  In Dwarf V2 DW_FORM_ref_addr was defined
+                as address-size even though it is a .debug_info
+                offset.  Fixed in Dwarf V3 to be offset-size.
+                */
+            unsigned length_size = 0;
+            if (context_version == 2) {
+                length_size = cu_context->cc_address_size;
+            } else {
+                length_size = cu_context->cc_length_size;
+            }
+            if (length_size == 4) {
+                READ_UNALIGNED(dbg, offset, Dwarf_Unsigned,
+                    attr->ar_debug_ptr, sizeof(Dwarf_ufixed));
+            } else if (length_size == 8) {
+                READ_UNALIGNED(dbg, offset, Dwarf_Unsigned,
+                    attr->ar_debug_ptr, sizeof(Dwarf_Unsigned));
+            } else {
+                _dwarf_error(dbg, error, DW_DLE_FORM_SEC_OFFSET_LENGTH_BAD);
+                return (DW_DLV_ERROR);
+            }
+        }
+        break;


and 

case DW_FORM_ref_addr:
+        if (cu_version == DW_CU_VERSION2) {
+            return (address_size);
+        }
         return (v_length_size);


Since compilers disagreed (understandably) I really need to know what DW_AT_producer is.

**Comment by TixoRebel** [comment] 2024-01-07 23:33
The section that's specifically causing problems for me is,
```    if (attrform == DW_FORM_addr
        /*  || attrform == DW_FORM_ref_addr Allowance of
            DW_FORM_ref_addr was a mistake. The value returned in that
            case is NOT an address it is a global debug_info
            offset (ie, not CU-relative offset within the CU
            in debug_info).
            The DWARF2 document refers to it as an address
            (misleadingly) in sec 6.5.4 where it describes
            the reference form. It is
            address-sized so that the linker can easily update it, but
            it is a reference inside the debug_info section. No longer
            allowed. */
        ) {
```
I'll take a look to see if I can generate a binary that demonstrates it, the compiler is part of an old devkit that I can't exactly share here.

**Comment by davea42** [comment] 2024-01-07 23:42
No one expects you to share your development tools.  
And yes,thanks, those lines you show  (from dwarf_form.c) are relevant too.

**Comment by TixoRebel** [comment] 2024-01-07 23:58
dwarfdump errors returning the following (the same thing I'm hitting),
```
.debug_info

dwarfdump ERROR:  ERROR: Failure reading CU header or DIE, corrupt DWARF:  DW_DLE_ATTR_FORM_BAD: In function dwarf_formaddr on seeing form  0x10  (DW_FORM_ref_addr). Attempting to continue.

dwarfdump ERROR:  printing .debug_info had a problem.:  DW_DLE_ATTR_FORM_BAD: In function dwarf_formaddr on seeing form  0x10  (DW_FORM_ref_addr). Attempting to continue.

There were 2 DWARF errors reported: see ERROR above.
```
Here's a segment from objdump if it's helpful,
```
  Number TAG (0)
   128      DW_TAG_typedef    [no children]
    DW_AT_type         DW_FORM_ref_addr
    DW_AT_name         DW_FORM_string
    DW_AT value: 0     DW_FORM value: 0
   129      DW_TAG_base_type    [no children]
    DW_AT_byte_size    DW_FORM_data4
    DW_AT_encoding     DW_FORM_data1
    DW_AT_name         DW_FORM_string
    DW_AT value: 0     DW_FORM value: 0
   130      DW_TAG_subrange_type    [no children]
    DW_AT_upper_bound  DW_FORM_data4
    DW_AT value: 0     DW_FORM value: 0
   131      DW_TAG_array_type    [has children]
    DW_AT_byte_size    DW_FORM_data4
    DW_AT_type         DW_FORM_ref_addr
    DW_AT value: 0     DW_FORM value: 0
   132      DW_TAG_subprogram    [has children]
    DW_AT_low_pc       DW_FORM_ref_addr
    DW_AT_high_pc      DW_FORM_ref_addr
    DW_AT_decl_line    DW_FORM_data2
    DW_AT_decl_file    DW_FORM_data2
    DW_AT_type         DW_FORM_ref_addr
    DW_AT_external     DW_FORM_flag
    DW_AT_frame_base   DW_FORM_block2
    DW_AT_name         DW_FORM_string
    DW_AT_sibling      DW_FORM_ref_addr
    DW_AT value: 0     DW_FORM value: 0
    ```

**Comment by davea42** [comment] 2024-01-08 00:12
Ah. Of course. Drat. No, that's of no help.

It was in 2014 when I received an object file compiled
by GO and *that* required v3 DW_FORM_ref_addr in a  DWARF2 output.

Can you try this?:

   do a hex dump of the first 1000 bytes of the .debug_info section, Email it.


`prevanders.net/software.html`
has words about hxdump and the source is
`prevanders.net/hxdump.c`

if you don't have a favorite dumper.

**Comment by TixoRebel** [comment] 2024-01-08 00:23
Sent, thank you for your help.

**Comment by davea42** [comment] 2024-01-08 00:38
Ok. Got it, and it's useful   Dwarf 2 as expected and I see the producer string.

Metroworks history is revealed by wikipedia and is quite interesting. I had heard
(vaguely) of CodeWarrior but knew nothing else.

**Comment by davea42** [comment] 2024-01-08 15:02
_dwarf_get_size_of_val() is *really* peculiar, it works differently than the other two places.
This is ... not right

In the failures you list from dwarfdump I am having difficulty understanding why we see those.
In other words, where we are when dwarf_formaddr() fails.  If you were to use a debugger on
dwarfdump  (running dwarfdump on your
object file) and break on dwarf_formaddr() and print the stack trace this would help immensely.
I hope there will be a tiny number of such calls before that dwarfdump error message appears.

**Comment by davea42** [comment] 2024-01-08 15:48
In a current libdarf source apply this patch:

```
---- a/src/lib/libdwarf/dwarf_die_deliv.c
+++ b/src/lib/libdwarf/dwarf_die_deliv.c
@@ -1107,6 +1107,14 @@ _dwarf_setup_base_address(Dwarf_Debug dbg,
             return DW_DLV_ERROR;
         }
     }
+    if (form == DW_FORM_ref_addr) {
+        /*  The old Macrowerks compiler did this
+            from confusion vs DW_FORM_addr.
+            Lets just say it is not good rather
+            than generating an error.
+        */
+        return DW_DLV_NO_ENTRY;
+    }
     lres = dwarf_formaddr(attr,
         &cucon->cc_low_pc,error);
     if (lres == DW_DLV_OK) {

```

Then rebuild libdwarf and dwarfdump and let's see if that helps.    I suspect it will not fully solve the problem.
I continue to work on this.

**Comment by davea42** [comment] 2024-01-08 16:27
Sending new patch by email. Now.

**Comment by davea42** [comment] 2024-01-08 18:14
Since this compiler is emitting DW_AT_low_pc with the bogus form DW_FORM_ref_addr
it means writing a simple function with one local variable and doing almost nothing
will generate DWARF usable for testing.

I mean as simple as t.c with:
```
#include <stdio.h>
int foo(void)
{
      int x = 1;
      return x+3;
}

cc -o t.c

```
If that is possible to do, it would be great.

**Comment by TixoRebel** [comment] 2024-01-08 20:13
Built and sent

**Comment by davea42** [comment] 2024-01-09 01:47
Received, but dwarfdump objects and so I tried readelfobj:

[ 6] 0x00000340 0x0000006c .rel.debug_info (0)(SHT_RELA)(1,0x5,0x0)
Warning: Section 6 .rel.debug_info is an SHT_RELA relocation section but its name  does not start with ".rela."
[ 7] 0x000003b0 0x00000000 .debug_macinfo (0)(SHT_PROGBITS)
[ 8] 0x000003b0 0x00000000 .debug_loc     (0)(SHT_PROGBITS)
[ 9] 0x000003b0 0x00000000  rel.debug_loc (0)(SHT_RELA)(1,0x8,0x0)
Warning: Section 9  rel.debug_loc is an SHT_RELA relocation section but its name  does not start with ".rela."


[11] 0x00000580 0x0000000c .rel.debug_line (0)(SHT_RELA)(1,0xa,0x0)
Warning: Section 11 .rel.debug_line is an SHT_RELA relocation section but its name  does not start with ".rela."
[12] 0x00000590 0x00000000 .debug_line    (0)(SHT_PROGBITS)
[13] 0x00000590 0x00000000 .rel.debug_line (0)(SHT_RELA)(1,0xc,0x0)
Warning: Section 13 .rel.debug_line is an SHT_RELA relocation section but its name  does not start with ".rela."

Well, that's weird, Warnings are from readelfobj, one of my projects.

More later.

**Comment by davea42** [comment] 2024-01-09 13:39
OK, I figured out how to work around the MacroWerks mistake of using DW_FORM_ref_addr.
Basically noticing the DW_AT_producer string contains the word Metrowerks
Have to do something about the relocation section mess they created (unsure what, yet).
If you build that tiny sample into an executable then the relocations vanish. Could you  do that?

Hopefully I can have something usable today.

**Comment by davea42** [comment] 2024-01-09 16:46
I have a usable libdwarf reader now.
Not only does it misname relocations sections but it has two .rel.debug_line sections (which is...wrong).

If it passess regression tests I will push to github.

**Comment by davea42** [comment] 2024-01-09 19:32
Pushed the revisions to libdwarf.   The library reads the DW_AT_producer string very early
and makes an internal note if the producer string contains 'Metrowerks' in it somewhere.

**Comment by TixoRebel** [comment] 2024-01-09 20:42
Because of some weirdness with the linker and target arch, I haven't been able to build a normal test executable, however, I can confirm that I am now able to load my elf and, for example, dump all srcfile lines.

**Comment by TixoRebel** [comment] 2024-01-09 21:05
For a bit of context, my goal is to read the ELF, modify the source file paths, and write it back to a new ELF (either with DWARF2 or newer debug data).

**Comment by davea42** [comment] 2024-01-09 21:14
Using the little sample above (and renaming the function to be 'main') then when you can build
an executable maybe send to me?

Given it's simple dwarf2 maybe dwarfgen could be persuaded to  read in, modify strings and the DW_FORM_ref_addr
and write it all out again as correct DWARF2.  Maybe.

**Comment by TixoRebel** [comment] 2024-01-09 21:27
I did try to just build the simple executable but it keeps refusing to link for one reason or another, I'll try a few more things tonight or at the latest tomorrow.

I'll give dwarfgen a look, at the very least it'll be a very good reference to build a tool on top of libdwarf for writing data.

**Comment by davea42** [comment] 2024-01-09 21:51
You will not be thrilled by dwarfgen.  It will be very interesting to know what sections are emitted
by Metrowerks. The simple test case emits  only .debug_info, .debug_line, .debug_abbrev
and .debug_pubnames has only a header. dwarfgen already kind of understands those section.

**Comment by TixoRebel** [comment] 2024-01-09 23:00
If I recall there were 5 sections with a debug information that it emitted in the actual ELF, I believe .debug_directories was one of them, but I'll post the list when I'm back at my computer.

**Comment by TixoRebel** [comment] 2024-01-13 15:45
The debug section that are emitted are,
```
  [385] .debug_abbrev     PROGBITS        00000000 251320 000132 01      0   0  1
  [386] .debug_info       PROGBITS        00000000 251460 5356d3 01      0   0  1
  [387] .debug_line       PROGBITS        00000000 786b40 11a31ba 01      0   0  1
  [388] .debug_pubnames   PROGBITS        00000000 1929d00 00b25e 01      0   0  1
  [389] .debug_overlay    PROGBITS        00000000 1934f60 0030bc 01      0   0  1
```

**Comment by davea42** [comment] 2024-01-14 19:04
Out of town for a few days...

**Comment by davea42** [comment] 2024-01-23 01:09
Well, .debug_overlay is...non standard.

IIRC you cannot provide a binary.  If you can, I can guarantee not to make it public.
In addition if .text and the like sections are zeroed (various tools can do that,
I have one I wrote myself) that would perhaps make you more comfortable.

It's not clear to me that further progress is possible on this...on this end...
without more data. davea42@linuxmail.org

**Comment by davea42** [comment] 2024-01-27 19:56
This support is included in today's v0.9.1 release, though not mentioned in the release
description or changes list.

**Comment by TixoRebel** [comment] 2024-01-27 20:02
Thanks! Sorry for the delay, things have been busy. I'm seeing what I can do about getting you a binary, however, I don't think there's any important information contained in the non-standard sections and everything important seems to be currently parsable by libdwarf.

**Comment by davea42** [comment] 2024-01-28 17:57
Well I'm happy it's working for you.  I am going to close this now, but if and when you find something else
create a new issue.

**Closed by davea42** 2024-01-28 17:57 UTC
