### ISSUE TITLE
ELF Parsing fails for files > 2 GB in Windows-64

### ISSUE THREAD

**Issue by rvijayc** [davea42/libdwarf-code#221] opened 2024-01-31 02:02 UTC
ELF parsing fails when loading files > 2GB on Windows-64 platform. This is due to the fact that we are using the 32-bit `lseek(...)` API instead of the 64-bit `_lseeki64(...)` API. The issue happens in places like this which use `lseek`.

https://github.com/davea42/libdwarf-code/blob/688afdc072c59d3a330c708e05c386fca991bb81/src/lib/libdwarf/dwarf_object_detector.c#L549

The parsing seems to succeed if I replace `lseek` with `_lseeki64` when `_WIN64` is defined. This change could potentially be made regardless of `_WIN64`, but I doubt anyone would attempt to read >2GB ELF files using a WIN32 program.

```c
#ifdef _WIN32
#ifdef HAVE_STDAFX_H
#include "stdafx.h"
#endif /* HAVE_STDAFX_H */
#include <io.h> /* lseek() off_t ssize_t */
/* WIN64 is only defined on 64-bit machines */
#ifdef _WIN64
#define lseek _lseeki64
#endif
#elif defined HAVE_UNISTD_H
#include <unistd.h> /* lseek() off_t */
#endif /* _WIN32 */
```

There is more information here: https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/lseek-lseeki64?view=msvc-170

I cannot share the ELF that I used, but I am wondering if you have tested this on very large ELF files on Windows? I am not sure if other file I/O also needs to be modified, but `lseek` certainly needs to support taking in 64-bit arguments and returning 64-bit integers.

Thanks!

**Comment by vtorri** [comment] 2024-01-31 05:05
there is also

```
    lsval  = (off_t)lseek(fd,(long)fileoffsetbase,SEEK_SET);
```

`long`is used by it's always a 32 bits type on Windows, contrary to Unix. It should not be used to follow pointer sire. Use intptr_t instead.

btw, try `git grep "(long)"` to see usage of `long` in the code

**Comment by vtorri** [comment] 2024-01-31 05:21
and `git grep "(unsigned long)"` too

**Comment by rvijayc** [comment] 2024-01-31 17:56
I agree that there may be quite a few places to update for large ELF file support on Windows, but I am looking for a "best bang for the buck" set of fixes to get me going. What I've found so far is modifying all `lseek` locations to use `_lseeki64` allows me to pass all my test cases. I'll send a PR once I get a chance (need to get approval from my org).

**Comment by davea42** [comment] 2024-02-02 00:46
Based on @rvijayc  I have corrected all the lseek instances to be workable with giant object files.
I have not figured out a way to actually test such  in a meaningful way.   
 Normal regression tests going on now.  Then msys build, test, then MSVC build.

**Comment by davea42** [comment] 2024-02-02 18:02
Note that, in _WIN64, as shown by a trivial C++ program in MSVC:
off_t is 32bits.  (surprized me...)
size_t  is 64 bits
uintptr_t is 64 bits.

ssize_t  seems not defined at all.

**Comment by davea42** [comment] 2024-02-02 19:42
So there were just three libdwarf .c files relevant to the lseek issue. But  a libdwarf function was using
off_t for offset, which is hopeless with windows as it is 32bit signed even for WIN64.
And using a signed type in the local argument list was silly, since we never use a negative seek value.

With adequate tests for negative lseek returns  we avoid all problems with type safety and large
object files.

I still don't know how to test adequately.

@rvijayc  If you could show us the section names and section sizes from the big object
that might help somehow.  As from readelf  -S or the like.

**Comment by vtorri** [comment] 2024-02-02 20:07
> ssize_t seems not defined at all.

it's SSIZE_T (uppercase)

**Comment by davea42** [comment] 2024-02-02 23:26
Yes, SSIZE_T,  it just struck me as odd that they ignored  ssize_t and did their own spelling.
This all-upppercase is quite normal for Windows basic types  (I realized that
yesterday) and is well documented on the web.  Being sceptical  I added 
prints of sizeof() various things to a tiny MSVC  project on my Win10 machine
to  verify  things we use.

I'v written two new internal functions in libdwarf in the new file dwarf_seekr,.c

+int _dwarf_readr(int fd, char *buf, Dwarf_Unsigned size,
+    Dwarf_Unsigned *sizeread);
+int _dwarf_seekr(int fd, Dwarf_Unsigned loc, int seektype,
+    Dwarf_Unsigned *out_loc);

All the ifdefs and references to io.h etc for Windows  and for
doing lseek() and read()  are in the  one file dwarf_seekr.c and the three
files needing lseek/read services no longer  have the _WIN32 tests etc

Hope to have it tested today.

**Comment by davea42** [comment] 2024-02-03 21:10
Well, one silly bug fixed, and testing going well.  
Linux/MacOS works. Working on the Win10 aspect (dwarf_seekr.c)

**Comment by davea42** [comment] 2024-02-03 21:26
About to try MSVC, but for msys2 gcc win64 we can handle >2G files, I believe. Pushed to github.

**Comment by davea42** [comment] 2024-02-03 21:52
Works linux/mac. works msys2. builds with MSVC, no warnings about data types.
On github now.

**Comment by davea42** [comment] 2024-02-04 00:32
Cleaned up various things.  In addition, I think the code is now capable of reading a multi-GB object,
though I still have not figured out how to create a testcase for that without
excessive effort.

**Comment by rvijayc** [comment] 2024-02-04 16:46
@davea42  Thanks for the changes. 

>  though I still have not figured out how to create a testcase for that without excessive effort. 

I can test this on >2G ELFs. I suppose if `dwarfdump <ELF>` runs till the end on the ELF file, its good enough?

**Comment by davea42** [comment] 2024-02-04 17:44
That would be good enough.  I look forward to hearing how it goes.

**Comment by rvijayc** [comment] 2024-02-04 18:08
I already started it on a very large ELF file and it seems to be running just fine for the last couple of hours. I think we are good. I will post here if anything goes wrong.

**Comment by davea42** [comment] 2024-02-07 16:21
Great news. Keep me up to date on this.

**Comment by rvijayc** [comment] 2024-02-07 16:24
It ended properly without any issues or crashes. I believe we are good to go.

**Comment by davea42** [comment] 2024-02-15 17:30
Ok, so closing this as it appears to work.

**Closed by davea42** 2024-02-15 17:30 UTC
