### ISSUE TITLE
I want to compile this libelfin library file under Windows

### ISSUE THREAD

**Issue by lovecomputer88** [davea42/libdwarf-code#141] opened 2022-12-03 14:48 UTC
I want to compile this libelfin library file under Windows so that I can develop in C++ under Windows, how do I do it? Thanks

**Comment by davea42** [comment] 2022-12-03 16:57
libdwarf is easily compiled on Windows MinGW64 Msys2.  The resulting dwarfdump
executable and libdwarf.dll
are... executable on Windows.   By building under Msys2 you get to use the same
build commands as in Linux/FreeBSD/Macos.  See README.md.

Maybe someone else with more Windows knowledge might have more to say.
Hope this helps.

**Comment by davea42** [comment] 2022-12-03 17:00
Oh. And the C code (all C) has been written so it should compile fine with a Windows C++ compiler. It has been done but I do not have any details. Sorry.

**Comment by lovecomputer88** [comment] 2022-12-04 15:41
Thanks，But there is a header file(<sys/mman.h>) that does not have a file under Windows? How do I deal with it

**Comment by vtorri** [comment] 2022-12-04 15:51
@lovecomputer88 which environment/IDE do you want to use ?

**Comment by lovecomputer88** [comment] 2022-12-04 15:54
thanks，the IDE is visual Studio 2019 or QT

**Comment by vtorri** [comment] 2022-12-04 16:12
@lovecomputer88 libdwarf can use cmake or meson to get a Visual Studio solution. With meson:

 * Install python3 (in case you don't have it). Open cmd.exe and be sure that python 3 is detected in cmd.exe
 * install meson like that : `pip3 install --user meson`
 * verify that meson is installed in cmd.exe : ` meson --version`
 * go to libdwarf subdirectory
 * launch :  `meson setup --backend vs builddir`

normally a Visual Studio solution is created in builddir/

**Comment by vtorri** [comment] 2022-12-04 16:14
the commands above can compile libdwarf on Windows with Visual Studio.

**Comment by lovecomputer88** [comment] 2022-12-07 00:50
[errinfo.txt](https://github.com/davea42/libdwarf-code/files/10171768/errinfo.txt)
[meson-log.txt](https://github.com/davea42/libdwarf-code/files/10171769/meson-log.txt)
I did it according to the given method, but it still didn't work, the attachment is the interface prompt information and the log made by meson. Thanks

**Comment by vtorri** [comment] 2022-12-07 07:27
@lovecomputer88 ok, @davea42 changed test/meson.build since the last time I tried.

@davea42 would it be possible to write the 3 shell scripts `test_debuglink-a.sh`, `test_debuglink-b.sh` and `test_jitreaderdiff.sh` in python ? That way, they will always work on linux or windows

the other way is to write them as batch scripts

**Comment by vtorri** [comment] 2022-12-07 13:00
@davea42 or add an option in meson_options.txt to disable tests

**Comment by davea42** [comment] 2022-12-07 16:24
the following diff of test/meson.build shows a nice way to solve the problem
Would you try this lovecomputer88? Let us know if that works for you.

 sh_exe = find_program('sh',required:true)
-foreach shscr : shscripttests
-  test_name = shscr[0]
-  message(test_name)
-  shexec_name = join_paths(projectbase,'test',test_name)
-  test(test_name,sh_exe,args: [shexec_name, projectbase ])
-endforeach
+if sh_exe.found()
+  foreach shscr : shscripttests
+    test_name = shscr[0]
+    message(test_name)
+    shexec_name = join_paths(projectbase,'test',test_name)
+    test(test_name,sh_exe,args: [shexec_name, projectbase ])
+  endforeach
+endif

**Comment by davea42** [comment] 2022-12-07 16:25
Ok that came out wrong
```
 sh_exe = find_program('sh',required:true)
-foreach shscr : shscripttests
-  test_name = shscr[0]
-  message(test_name)
-  shexec_name = join_paths(projectbase,'test',test_name)
-  test(test_name,sh_exe,args: [shexec_name, projectbase ])
-endforeach
+if sh_exe.found()
+  foreach shscr : shscripttests
+    test_name = shscr[0]
+    message(test_name)
+    shexec_name = join_paths(projectbase,'test',test_name)
+    test(test_name,sh_exe,args: [shexec_name, projectbase ])
+  endforeach
+endif

```

**Comment by davea42** [comment] 2022-12-07 16:29
I'll also be adding` if py3_exe.found()` to test/meson.build too, using the same approach as
for sh_exe.

**Comment by lovecomputer88** [comment] 2022-12-08 08:26
I did the following work
1 Refer to davea42 tips,edit file( test/meson.build)
2 launch : meson setup --backend vs builddir 
But  it still didn't work, the attachment is the interface prompt information and the log made by meson. Thanks
[errorinfo.txt](https://github.com/davea42/libdwarf-code/files/10183505/errorinfo.txt)
[mesonBuild.zip](https://github.com/davea42/libdwarf-code/files/10183506/mesonBuild.zip)
[meson-log.txt](https://github.com/davea42/libdwarf-code/files/10183507/meson-log.txt)

**Comment by vtorri** [comment] 2022-12-08 08:36
@davea42 the problem is:

 sh_exe = find_program('sh',required:true)

you explicitely require the 'sh' command

@lovecomputer88 as a temporary fix, in the  toplevel meson.build, remove the line `subdir('test')` to avoid the build of the tests (which you don't need, I think)

**Comment by lovecomputer88** [comment] 2022-12-08 09:19
After following the prompts to remove subdir('test'), after compiling, no generated library files were found
[outinfo.txt](https://github.com/davea42/libdwarf-code/files/10183936/outinfo.txt)

**Comment by vtorri** [comment] 2022-12-08 10:14
@lovecomputer88 no .sln in builddir/ ?

**Comment by davea42** [comment] 2022-12-08 19:18
Iit turns out find_installation() defaults to requred:true
so that  py3.exe line in test/meson.build should be changed
as if it fails some tests will not be run, but that is ok.

py3_exe = import('python').find_installation(required:false)

**Comment by lovecomputer88** [comment] 2022-12-10 13:34
As done as above, there are also files in the directory, but the compilation with vs2022 is unsuccessful, there is no dll or lib, prompts a C2220 error, and the following warning is considered an error
[builddir.zip](https://github.com/davea42/libdwarf-code/files/10200176/builddir.zip)
![Uploading errorImage.png…]()

**Comment by davea42** [comment] 2022-12-10 16:41
Looking through the zip file content I don't find anything with the digit set 2220 nor C222
If that is a compiler warning/error that suggests somewhere in the source there is
something that your compiler is noticing.  Something we could change in the source.
But I don't know what, in the library/dwarfdump source is provoking the warning/error.

Compilers continue to be improve at noticing source that is questionable, so I'm not surprised
if this is a new warning.

**Comment by davea42** [comment] 2022-12-11 19:33
The use of Dwarf_Signed in dwarf_alloc.c is ...peculiar...
Unjustified. 

This is a revised libdwarf/alloc.c  (inside the zip) which...may or may not
help.    It has more changes  than I wanted to provide as a diff).
I hope you will try it and let us know what happens.  Another photo
of any compilation warnings would be good.

So.  the whole source file is attached.
 
[dwarf_alloc.zip](https://github.com/davea42/libdwarf-code/files/10203066/dwarf_alloc.zip)

**Comment by davea42** [comment] 2022-12-11 21:33
Ignore that dwarf_alloc.zip,  In a full  set of regression tests I'm having
a set of failures. Something wrong.  I'll get back to you, but surely not today,
busy with scheduled events the rest of today.  
Sorry.

**Comment by davea42** [comment] 2022-12-11 22:00
[dwarf_alloc.zip](https://github.com/davea42/libdwarf-code/files/10203375/dwarf_alloc.zip)

Fixed the mistake, regression tests running fine now.  (Not complete though,
so no guarantees it is really right. Hope to run those guarantees in the next few hours.)
This is NOT fully tested dwarf_alloc.c.    But the question of the moment is:
will this avoid compiler warnings? get you further?

**Comment by lovecomputer88** [comment] 2022-12-12 03:06
thanks!but after I replaced this file(dwarf_alloc.c),the compilation with vs2022 is unsuccessful, there is no dll or lib, There are 12 files that prompt the same error(C2220), and the following warning is considered an error
src\lib\libdwarf\dwarf_debugaddr.c	134	
src\lib\libdwarf\dwarf_debuglink.c	1	
...
src\bin\dwarfdump\dd_attr_form.c	119	

![errorImage](https://user-images.githubusercontent.com/48816896/206952153-a052af0b-68dd-496a-8300-2f3b63d400b5.png)

**Comment by vtorri** [comment] 2022-12-12 07:23
I have some time this morning, i'll look at this in detail in the next 3 hours

**Comment by vtorri** [comment] 2022-12-12 09:20
@lovecomputer88 i'll wait for @davea42 to look at my PR and the 2 issues that I have opened.

btw, do you only need libdwarf, or also dwarfdump ?

**Comment by davea42** [comment] 2022-12-12 19:27
I certainly hope dwrfdump and libdwarf  will build and run just fine for you. 
We definitely want it to do so.  I just pushed updated code which might (I hope)
fix the compiler warnings.  All the warnings were sensible  and  I
was happy to fix the code.  vtorri provided me compilers warnings in English from
Windows, which really helped .... my language skills are non-existent except for English (sorry).

**Comment by vtorri** [comment] 2022-12-12 20:01
@davea42 and about the PR ?

**Comment by lovecomputer88** [comment] 2022-12-13 06:51
thanks!but after I replaced this file,the compilation with vs2022 is unsuccessful, there is no dll or lib, There are  prompt the same error(C2220), and the following warning is considered an error
I only compile this file(dwarf-0),It also prompts a C2220 error(\src\lib\libdwarf\dwarf_alloc.c(608,24): error C2220: the following warning is considered an error
![errorImage](https://user-images.githubusercontent.com/48816896/207246566-6db3af1a-87a7-4d4a-86c3-f2611b29271f.png)
), and the errors of other files behind are mostly caused by this

**Comment by vtorri** [comment] 2022-12-13 06:53
yes, other errors on my side too. I'll report them in an issue

**Comment by davea42** [comment] 2022-12-13 18:54
FYI. I am now testing with no UNUSEDARG anywhere in the source and using (void)name;
everywhere appropriate.
and it works fine with gcc and clang.  Once the clang/freebsd tests pass I will
commit and push all this.  Then I can address the warnings errors vtorri will 
report.  Of course vtorri will want to pull the latest (sorry) once I push to github.

**Comment by lovecomputer88** [comment] 2022-12-20 09:51
I see the update, is the issue I found resolved?

**Comment by vtorri** [comment] 2022-12-20 10:40
i think there are some more. I wait for @davea42 to finish to fix the issue. Then I'll run VS again to see if there are more

**Comment by davea42** [comment] 2022-12-20 17:52
On 12/20/22 02:40, vtorri wrote:
> i think there are some more. I wait for @davea42 
> <https://github.com/davea42> to finish to fix the issue. Then I'll run 
> VS again to see if there are more
> 
> —

Sorry, I thought you knew.  I've fixed all the  warnings in the open 
issues.  Given I have no way to test against that compiler
I cannot be sure I got them all, but I expect I did.

All pushed to github.

Please send more when you have time.

DavidA


-- 
What's another word for Thesaurus?  -- Steven Wright

**Comment by davea42** [comment] 2023-02-10 17:36
I am uncertain of the status of the requested Windows build.
I hope that current libdwarf (nearing the release of 0.6.0 on Feb 20,2023)
builds ok. There have been many changes/fixes applied.

So I am closing this and I request that 
if you are still having a build problem...
Please  open a new issue with whatever
build problems you have with current  libdwarf source.

**Closed by davea42** 2023-02-10 17:36 UTC
