### ISSUE TITLE
search libelf even if libdwarf doesn't need anymore

### ISSUE THREAD

**Issue by flagarde** [davea42/libdwarf-code#170] opened 2023-06-27 05:15 UTC
Hello, Thank you for this nice library. If I understand correctly the library desn't need anymore the libelf library however it still try to find it. This is correct ? In case the libelf is used for examples/tests or programs maybe this checks would be done olnly i we compile sucg things ? Would you accept a PR if it's the case ?

**Comment by davea42** [comment] 2023-06-27 15:57
It still looks for libelf because dwarfgen (which is useless to you) currently requires it.
A project is underway to remove the need for libelf in dwarfgen and that will mean
all traces, all references to libelf, libelf.h, and elf.h will be removed from the entire
project.  I am hoping it will be done in under a month, much progress has been made
in dwarfgen (in a local branch).   So my suggestion to you is to just be patient, all
traces everywhere in this project (build systems, and source) will soon be gone.

I am happy to hear you are in favor of this coming change!

**Comment by davea42** [comment] 2023-06-28 20:52
I have removed all libelf from dwarfgen,
generating Elf from dwarfgen.cc directly.  
So far it looks good for what it needs to do.
Now  running a full regression test on everything.
If that works as expected I will merge into main and remove all the libelf/LIBELF
and related from all build scripts. Maybe today.

**Comment by davea42** [comment] 2023-06-29 23:39
All tests pass so I have pushed the changes to github.
(yes the regressiontests had mention of libelf and all that is gone now).


If anyone finds any dependency on libelf libelf.h or elf.h please
let us know as soon as convenient.  Thank you.

**Comment by flagarde** [comment] 2023-06-30 03:53
So nice, thx for your hard work !

**Comment by vtorri** [comment] 2023-06-30 04:26
https://github.com/davea42/libdwarf-code/blob/main/meson.build#L189
https://github.com/davea42/libdwarf-code/blob/main/meson_options.txt#L2C12-L2C15

**Comment by davea42** [comment] 2023-06-30 16:32
Thanks. Just pushed  fixed versions.

**Comment by davea42** [comment] 2023-07-03 23:52
The push fulfilled the original request and improves the build
for everyone (no messy setups for libelf as libelf is never
used).  So lets close this.

**Closed by davea42** 2023-07-03 23:52 UTC
