### ISSUE TITLE
dwarf error 48 DW_DLE_VERSION_STAMP_ERROR: The .debug_addr version should be 5 but we find 0 instead.

### ISSUE THREAD

**Issue by jeremy-rifkin** [davea42/libdwarf-code#243] opened 2024-05-26 02:25 UTC
I'm trying to use `dwarf_debug_addr_table` to get entries from `.debug_addr` however I'm running into an error

```
dwarf error 48 DW_DLE_VERSION_STAMP_ERROR: The .debug_addr version should be 5 but we find 0 instead.
```

This is happening both in my own code and from `src/bin/dwarfdump/dwarfdump --print-debug-addr path/to/cpptrace/build/demo`:

```
ERROR: dwarfdump found no dwarfdump.conf file in any of the standard places
(precede all arguments with option --show-dwarfdump-conf to see what file paths tried)
If no print/check arguments also provided dwarfdump may silently just stop.
Frame not configured due to configure error(s), using generic 100 registers.
Frame section access suppressed.

.debug_addr


src/bin/dwarfdump/dwarfdump ERROR:  printing the .debug_addr section had a problem.:  DW_DLE_VERSION_STAMP_ERROR: The .debug_addr version should be 5 but we find 0 instead.. Attempting to continue.

There were 2 DWARF errors reported: see ERROR above.
```

I built the `demo` binary that is causing problems with `g++ -g -gsplit-dwarf`.

Additional info that may be helpful:

`readelf -S build/demo`:

```
There are 44 section headers, starting at offset 0x4527f8:

Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .interp           PROGBITS         0000000000000318  00000318
       000000000000001c  0000000000000000   A       0     0     1
  [ 2] .note.gnu.pr[...] NOTE             0000000000000338  00000338
       0000000000000030  0000000000000000   A       0     0     8
  [ 3] .note.gnu.bu[...] NOTE             0000000000000368  00000368
       0000000000000024  0000000000000000   A       0     0     4
  [ 4] .note.ABI-tag     NOTE             000000000000038c  0000038c
       0000000000000020  0000000000000000   A       0     0     4
  [ 5] .gnu.hash         GNU_HASH         00000000000003b0  000003b0
       000000000000003c  0000000000000000   A       6     0     8
  [ 6] .dynsym           DYNSYM           00000000000003f0  000003f0
       0000000000001008  0000000000000018   A       7     1     8
  [ 7] .dynstr           STRTAB           00000000000013f8  000013f8
       00000000000018dd  0000000000000000   A       0     0     1
  [ 8] .gnu.version      VERSYM           0000000000002cd6  00002cd6
       0000000000000156  0000000000000002   A       6     0     2
  [ 9] .gnu.version_r    VERNEED          0000000000002e30  00002e30
       0000000000000180  0000000000000000   A       7     3     8
  [10] .rela.dyn         RELA             0000000000002fb0  00002fb0
       0000000000001e78  0000000000000018   A       6     0     8
  [11] .rela.plt         RELA             0000000000004e28  00004e28
       0000000000000d20  0000000000000018  AI       6    26     8
  [12] .init             PROGBITS         0000000000006000  00006000
       000000000000001b  0000000000000000  AX       0     0     4
  [13] .plt              PROGBITS         0000000000006020  00006020
       00000000000008d0  0000000000000010  AX       0     0     16
  [14] .plt.got          PROGBITS         00000000000068f0  000068f0
       0000000000000030  0000000000000010  AX       0     0     16
  [15] .plt.sec          PROGBITS         0000000000006920  00006920
       00000000000008c0  0000000000000010  AX       0     0     16
  [16] .text             PROGBITS         0000000000007200  00007200
       0000000000111011  0000000000000000  AX       0     0     64
  [17] .fini             PROGBITS         0000000000118214  00118214
       000000000000000d  0000000000000000  AX       0     0     4
  [18] .rodata           PROGBITS         0000000000119000  00119000
       0000000000033d85  0000000000000000   A       0     0     32
  [19] .eh_frame_hdr     PROGBITS         000000000014cd88  0014cd88
       0000000000007c3c  0000000000000000   A       0     0     4
  [20] .eh_frame         PROGBITS         00000000001549c8  001549c8
       000000000001ffb4  0000000000000000   A       0     0     8
  [21] .gcc_except_table PROGBITS         000000000017497c  0017497c
       00000000000023a0  0000000000000000   A       0     0     4
  [22] .init_array       INIT_ARRAY       0000000000177b20  00177b20
       0000000000000058  0000000000000008  WA       0     0     8
  [23] .fini_array       FINI_ARRAY       0000000000177b78  00177b78
       0000000000000008  0000000000000008  WA       0     0     8
  [24] .data.rel.ro      PROGBITS         0000000000177b80  00177b80
       0000000000000d40  0000000000000000  WA       0     0     32
  [25] .dynamic          DYNAMIC          00000000001788c0  001788c0
       0000000000000220  0000000000000010  WA       7     0     8
  [26] .got              PROGBITS         0000000000178ae0  00178ae0
       0000000000000508  0000000000000008  WA       0     0     8
  [27] .data             PROGBITS         0000000000179000  00179000
       0000000000000a20  0000000000000000  WA       0     0     32
  [28] .bss              NOBITS           0000000000179a20  00179a20
       0000000000000730  0000000000000000  WA       0     0     32
  [29] .comment          PROGBITS         0000000000000000  00179a20
       0000000000000026  0000000000000001  MS       0     0     1
  [30] .debug_aranges    PROGBITS         0000000000000000  00179a50
       000000000000f630  0000000000000000           0     0     16
  [31] .debug_info       PROGBITS         0000000000000000  00189080
       0000000000000f19  0000000000000000           0     0     1
  [32] .debug_abbrev     PROGBITS         0000000000000000  00189f99
       0000000000000619  0000000000000000           0     0     1
  [33] .debug_line       PROGBITS         0000000000000000  0018a5b2
       000000000006e89e  0000000000000000           0     0     1
  [34] .debug_str        PROGBITS         0000000000000000  001f8e50
       00000000000016f8  0000000000000001  MS       0     0     1
  [35] .debug_ranges     PROGBITS         0000000000000000  001fa548
       0000000000000180  0000000000000000           0     0     1
  [36] .debug_addr       PROGBITS         0000000000000000  001fa6c8
       0000000000012cb8  0000000000000000           0     0     1
  [37] .debug_line_str   PROGBITS         0000000000000000  0020d380
       00000000000016fc  0000000000000001  MS       0     0     1
  [38] .debug_rnglists   PROGBITS         0000000000000000  0020ea7c
       0000000000003a1f  0000000000000000           0     0     1
  [39] .debug_gnu_p[...] PROGBITS         0000000000000000  0021249b
       0000000000109a31  0000000000000000           0     0     1
  [40] .debug_gnu_p[...] PROGBITS         0000000000000000  0031becc
       000000000009e818  0000000000000000           0     0     1
  [41] .symtab           SYMTAB           0000000000000000  003ba6e8
       000000000001fcc8  0000000000000018          42   3688     8
  [42] .strtab           STRTAB           0000000000000000  003da3b0
       0000000000078266  0000000000000000           0     0     1
  [43] .shstrtab         STRTAB           0000000000000000  00452616
       00000000000001db  0000000000000000           0     0     1
```

`readelf -wA build/demo`:
```
<A bunch of "Found separate debug object file" entries...>

Contents of the .debug_addr section (loaded from build/demo):

  For compilation unit at offset 0:
        Index   Address
        0:      0000000000007442
        1:      000000000000746a
        2:      0000000000007781
        3:      00000000000072e9
        4:      0000000000007650
        5:      00000000000073ab
        6:      00000000000073f3
        7:      0000000000007419
        8:      000000000000767a
        9:      00000000000075d9
        10:     00000000000076c4
        11:     0000000000007701
        12:     000000000000737f
        13:     000000000000745a
        14:     00000000000077c7
        15:     000000000000751d
        16:     0000000000007794
        17:     000000000000748a
        18:     00000000000077e6
        19:     00000000000074e6
        20:     0000000000007540
        21:     0000000000007822
        22:     00000000000075a2
        23:     00000000000075f4
        24:     0000000000007592
        25:     0000000000007606
        26:     0000000000007854
        27:     000000000000773e
        28:     0000000000007881
        29:     00000000000078a8
        30:     00080005000010ac
  For compilation unit at offset 0x34:
        Index   Address
readelf: Warning: Corrupt .debug_addr section: expecting header size of 8 or 16, but found 0 instead
```

Interestingly llvm-dwarfdump also errors here `llvm-dwarfdump-18 --debug-addr path/to/cpptrace/build/demo`:
```
path/to/cpptrace/build/demo:  file format elf64-x86-64

.debug_addr contents:
error: address table at offset 0x0 has unsupported version 0
error: section is not large enough to contain an address table at offset 0x7446 with a unit_length value of 0x24040000
```

And the main executable's CU in case it provides any clues about how the split dwarf is being done here:
```
build/demo:	file format elf64-x86-64

.debug_info contents:
0x00000000: Compile Unit: length = 0x00000030, format = DWARF32, version = 0x0004, abbr_offset = 0x0000, addr_size = 0x08 (next unit at 0x00000034)

0x0000000b: DW_TAG_compile_unit
              DW_AT_ranges	(0x00000000
                 [0x00000000000072e9, 0x0000000000007441)
                 [0x0000000000007442, 0x000000000000746a)
                 [0x000000000000746a, 0x0000000000007489)
                 [0x000000000000748a, 0x00000000000074e6)
                 [0x00000000000074e6, 0x0000000000007540)
                 [0x0000000000007540, 0x0000000000007592)
                 [0x0000000000007592, 0x00000000000075a1)
                 [0x00000000000075a2, 0x00000000000075f4)
                 [0x00000000000075f4, 0x0000000000007606)
                 [0x0000000000007606, 0x0000000000007650)
                 [0x0000000000007650, 0x000000000000767a)
                 [0x000000000000767a, 0x00000000000076c4)
                 [0x00000000000076c4, 0x0000000000007701)
                 [0x0000000000007701, 0x000000000000773e)
                 [0x000000000000773e, 0x0000000000007781)
                 [0x0000000000007781, 0x0000000000007793)
                 [0x0000000000007794, 0x00000000000077c7)
                 [0x00000000000077c7, 0x00000000000077e6)
                 [0x00000000000077e6, 0x0000000000007822)
                 [0x0000000000007822, 0x0000000000007854)
                 [0x0000000000007854, 0x0000000000007881)
                 [0x0000000000007881, 0x00000000000078a8)
                 [0x00000000000078a8, 0x00000000000078c7))
              DW_AT_low_pc	(0x0000000000000000)
              DW_AT_stmt_list	(0x00000000)
              DW_AT_GNU_dwo_name	("test/CMakeFiles/demo.dir/demo.cpp.dwo")
              DW_AT_comp_dir	("path/to/cpptrace/build")
              DW_AT_GNU_pubnames	(true)
              DW_AT_GNU_addr_base	(0x00000000)
              DW_AT_GNU_dwo_id	(0x264df22d18809c35)
              DW_AT_GNU_ranges_base	(0x00000000)
```

**Comment by jeremy-rifkin** [comment] 2024-05-26 05:16
Here's a hexdump of the start of the .debug_addr section as well
```

Hex dump of section '.debug_addr':
  0x00000000 42740000 00000000 6a740000 00000000 Bt......jt......
  0x00000010 81770000 00000000 e9720000 00000000 .w.......r......
  0x00000020 50760000 00000000 ab730000 00000000 Pv.......s......
  0x00000030 f3730000 00000000 19740000 00000000 .s.......t......
  0x00000040 7a760000 00000000 d9750000 00000000 zv.......u......
  0x00000050 c4760000 00000000 01770000 00000000 .v.......w......
  0x00000060 7f730000 00000000 5a740000 00000000 .s......Zt......
  0x00000070 c7770000 00000000 1d750000 00000000 .w.......u......
  0x00000080 94770000 00000000 8a740000 00000000 .w.......t......
  0x00000090 e6770000 00000000 e6740000 00000000 .w.......t......
  0x000000a0 40750000 00000000 22780000 00000000 @u......"x......
  0x000000b0 a2750000 00000000 f4750000 00000000 .u.......u......
  0x000000c0 92750000 00000000 06760000 00000000 .u.......v......
  0x000000d0 54780000 00000000 3e770000 00000000 Tx......>w......
  0x000000e0 81780000 00000000 a8780000 00000000 .x.......x......
  0x000000f0 ac100000 05000800 f2b20000 00000000 ................
  0x00000100 7ab50000 00000000 34b30000 00000000 z.......4.......
  0x00000110 e4050100 00000000 bc0d0100 00000000 ................
  0x00000120 62b30000 00000000 260d0100 00000000 b.......&.......
  0x00000130 90b30000 00000000 1f140100 00000000 ................
  0x00000140 5e140100 00000000 70140100 00000000 ^.......p.......
  0x00000150 5e180100 00000000 98f40000 00000000 ^...............
  0x00000160 2c9a1700 00000000 179e0000 00000000 ,...............
  ```

**Comment by jeremy-rifkin** [comment] 2024-05-26 05:43
The dwarf standard mentions headers being involved in the debug_addr section however https://gcc.gnu.org/wiki/DebugFission mentions a different headerless encoding, and maybe this is what gcc happens to be emitting
> .debug_addr -- This section contains relocated references to loadable sections in the program. No header is required; the base of each compilation unit's contribution to the section is given by the DW_AT_addr_base attribute of the skeleton DW_TAG_compile_unit DIE in the .debug_info section. Each entry is 4 or 8 bytes, depending on the address_size field of the compilation unit header in the .debug_info section.

This seems in-line with how libbacktrace appears to resolve address indexes https://github.com/ianlancetaylor/libbacktrace/blob/11427f31a64b11583fec94b4c2a265c7dafb1ab3/dwarf.c#L1427, unless I am mistaken. If it is an issue of two competing encodings for this section I’m unsure of what could be used to differentiate the two.

**Comment by davea42** [comment] 2024-05-26 15:02
Given that wiki entry it is clear GNU's intent about the section was
 not what the DWARF committee eventually specified.

So I wonder what DWARF version .debug_info is. 4?  5? Something else?

Can you provide a (small?)  .dwo or object with the problem? One that is non-proprietary so I can
include it in regressiontests?
My intent is to figure out how to know when to expect the non-standard .debug_addr section.
But I need an example to verify the revised code works, of course.

**Comment by davea42** [comment] 2024-05-26 15:08
The simple way to eliminate that annoying dwarfdump.conf message is to
copy a dwarfdump.conf as in
`cp libdwarf-code/src/bin/dwarfdump/dwarfdump.conf ~/dwarfdump.conf`
for example

**Comment by jeremy-rifkin** [comment] 2024-05-26 15:46
Thanks Dave! Here's a small example (built from https://github.com/jeremy-rifkin/cpptrace/tree/dev with `cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DCPPTRACE_BUILD_TESTING=On -DCMAKE_CXX_FLAGS="-gsplit-dwarf" -DCMAKE_C_FLAGS="-gsplit-dwarf" -DBUILD_SHARED_LIBS=On`): [demo-and-dwo.zip](https://github.com/davea42/libdwarf-code/files/15448057/demo-and-dwo.zip). I think dwarf 4 is being used.

**Comment by jeremy-rifkin** [comment] 2024-05-26 16:36
It looks like if I use `-g -gsplit-dwarf -gdwarf-5` the section is properly generated

**Comment by davea42** [comment] 2024-05-26 16:36
Thanks for the object files.
These are DWARF 4 objects. Here gcc is adding an extension to the DWARF4 specification.

So I need to add a bit of code to libdwarf so libdwarf recognizes that in DWARF4   .debug_addr
is in a different format than in DWARF5.

**Comment by davea42** [comment] 2024-05-26 20:40
Yes to your note about dwarf-5.  Makes sense to me.

 In DWARF4 gcc could add .debug_addr extension way before the committee
got around to specifying the section for DWARF5 (and that is ok).  But gcc
did the right thing for DWARF5. 
 With DWARF4 .debug_addr the API function dwarf_debug_addr_table()
cannot work (gets error), But that is ok, it is the reason the committee added
the header-per-table for DWARF5.

Now I will look at processing debug_addr indexes in reading DIEs.

**Comment by jeremy-rifkin** [comment] 2024-05-26 23:15
It'd be helpful if information from the DWARF4 .debug_addr could somehow be exposed through libdwarf, if at all possible. If not through the `dwarf_debug_addr_table` API maybe another function?

**Comment by davea42** [comment] 2024-05-27 14:22
With
`dwarfdump -a --file-tied=demo -i demo.cpp.dwo `
there are no errors reported by dwarfdump.
The gnu .debug_addr is in demo, so  accessing demo.cpp.dwo
without the tied-file will get the debug_addr message.

**Comment by davea42** [comment] 2024-05-27 14:35
The reason there are no errors (once the tied file is available on reading
demo.cpp.dwo) is that the meaning of DW_AT_addr_base (and DW_AT_GNU_addr_base) is the same for DWARF4 and for the DWARF4 .debug _addr sections.

So it appears to me that there is no libdwarf bug here.

**Comment by davea42** [comment] 2024-05-27 14:52
To allow printing of raw .debug_addr it will be necessary to 
add a new API function and supply various arguments like
address_size etc and offset size.  And have dwarfdump
call it on DWARF4 objects.   I'm not sure how useful that
will be.

**Comment by jeremy-rifkin** [comment] 2024-05-27 15:21
I see what you mean about `dwarfdump -a --file-tied=demo -i demo.cpp.dwo` working. Does that mean libdwarf is already handling the gnu .debug_addr format?

**Comment by davea42** [comment] 2024-05-27 17:19
Currently running regression tests on printing a raw DWARF4 extension
 .debug_addr section.   One must ensue that .debug_info was read
for --print-debug-addr to work on DWARF4.  It assumes all
CUs are DWARF4 if the initial .debug_info CU is DWARF4.
Will likely work ok in most cases.

**Comment by davea42** [comment] 2024-05-27 17:50
Pushed support for printing .debug_addr with --print-debug-addr , the GNU extension
of DWARF4.  In addition if one has called dwarf_cu_header_e or _d
at least once then dwarf_debug_addr_table() will work on DWARF4 too.

**Comment by davea42** [comment] 2024-05-27 21:21
MSVC had a warning: added a cast in the new dwarf_debugaddr.c code.
Also fixed  omissions in meson.build. needed to set PROJECT_VERSION string
two places.

**Comment by davea42** [comment] 2024-05-29 15:37
I think this issue is fixed, fix now on github.

**Comment by davea42** [comment] 2024-06-08 17:48
Fixed. Closing.

**Closed by davea42** 2024-06-08 17:48 UTC

**Comment by jeremy-rifkin** [comment] 2024-06-10 03:55
Thank you so much!
