### ISSUE TITLE
scripts/run-all-tests.sh missing shell backtick

### ISSUE THREAD

**Issue by rmustacc** [davea42/libdwarf-code#247] opened 2024-06-15 19:12 UTC
While incorrectly following the directions on https://www.prevanders.net/dwarf.html, I tried to run `scripts/run-all-tests.sh` and found that it was failing on both illumos and Ubuntu regardless of the shell used (bash, ksh93, dash). It appears that line 14 is missing the terminating ` character which causes it not to parse (see [here](https://github.com/davea42/libdwarf-code/blob/main/scripts/run-all-tests.sh#L14)). Not sure if this is still used much or not, but applying that let the script be parsed at least. I thought it might be helpful to let you know.

**Comment by davea42** [comment] 2024-06-16 01:11
Thanks for noticing. It's something I have not run recently,
but I appreciate the correction.
The change has been pushed to github.

**Comment by davea42** [comment] 2024-06-16 01:53
The script assumes that regressiontests still use configure. Oops.
They use meson now. Speeds up the build nicely.

So the script is still broken. I will fix soon.

**Comment by davea42** [comment] 2024-06-16 01:53
As I said. Not fixed

**Comment by davea42** [comment] 2024-06-16 17:41
Now it runs ok.  I altered the regressiontests part to use the newer
meson builds as regressiontests no longer support configure builds.

Of course configure builds still work for libdwarf/dwarfdump. 
Just not in regressiontests, which only supports a single build mechanism.

**Comment by davea42** [comment] 2024-06-16 17:42
So now I am closing this. Works for me now.

**Closed by davea42** 2024-06-16 17:42 UTC
