### ISSUE TITLE
Issue with range handling for gcc 10's dwarf 4 split-dwarf output

### ISSUE THREAD

**Issue by jeremy-rifkin** [davea42/libdwarf-code#265] opened 2024-10-06 17:44 UTC
Hi,
I'm seeing a discrepancy between ranges reported by libdwarf's dwarfdump and llvm's dwarfdump for a subprogram DIE:

Llvm dwarfdump:
```
0x0008722c:   DW_TAG_subprogram
                DW_AT_external	(true)
                DW_AT_name	("stacktrace_basic")
                DW_AT_decl_file	(0x07)
                DW_AT_decl_line	(27)
                DW_AT_decl_column	(31)
                DW_AT_linkage_name	("_Z16stacktrace_basicv")
                DW_AT_ranges	(0x00022030
                   [0x000000000002d400, 0x000000000002df68)
                   [0x000000000000e94d, 0x000000000000ea14))
                DW_AT_frame_base	(DW_OP_call_frame_cfa)
                DW_AT_GNU_all_tail_call_sites	(true)
                DW_AT_sibling	(0x0008e081)
```

Libdwarf dwarfump:
```
< 1><0x0008722c GOFF=0x0008722c>    DW_TAG_subprogram <abbrev 399 ABGOFF = 0x00001eeb count = 0x0000000a>
                                      DW_AT_external              yes(1) <form DW_FORM_flag_present 25>
                                      DW_AT_name                  (indexed string: 0x000013ef)stacktrace_basic <form DW_FORM_GNU_str_index 7938>
                                      DW_AT_decl_file             0x00000007 <form DW_FORM_data1 11>
                                      DW_AT_decl_line             0x0000001b <form DW_FORM_data1 11>
                                      DW_AT_decl_column           0x0000001f <form DW_FORM_data1 11>
                                      DW_AT_linkage_name          (indexed string: 0x000008be)_Z16stacktrace_basicv <form DW_FORM_GNU_str_index 7938>
                                      DW_AT_ranges                0x00022030 <form DW_FORM_sec_offset 23>
  ranges: 3 at .debug_ranges offset 139312 (0x00022030)  ( base addr 0x00000000) (48 bytes)
   [ 0] range entry  raw: 0x00022044,  0x0002205b cooked: 0x00022044,  0x0002205b
   [ 1] range entry  raw: 0x0002205b,  0x00022075 cooked: 0x0002205b,  0x00022075
   [ 2] range end    0,0
                                      DW_AT_frame_base            len 0x0001: 0x9c:  <form DW_FORM_exprloc 24>
                                          DW_OP_call_frame_cfa
                                      DW_AT_GNU_all_tail_call_sites yes(1) <form DW_FORM_flag_present 25>
                                      DW_AT_sibling               <0x0008e081 GOFF=0x0008e081> <form DW_FORM_ref4 19>
```

The output from llvm dwarfdump is what I expect and I believe it to be correct in this case.

Here are the relevant objects: [br.zip](https://github.com/user-attachments/files/17270390/br.zip)

Llvm command: `llvm-dwarfdump-18 unittest --dwo`

Dwarfdump command: `dwarfdump -i -M -G  -vv --file-tied=unittest test/CMakeFiles/unittest.dir/unit/stacktrace.cpp.dwo`

I came across this while testing recent versions of libdwarf with my library, the specific code I'm testing on my library is https://github.com/jeremy-rifkin/cpptrace/commit/1c9d22344b64ed0442d1e44b60ae80d89b395930.

The specific configurations showing [failures](https://github.com/jeremy-rifkin/cpptrace/actions/runs/11203482081/job/31140784033) are:
```
| compiler   | stdlib    | sanitizers | build_type     | shared | has_dl_find_object | split_dwarf | dwarf_version |
| g++-10     | libstdc++ | OFF        | RelWithDebInfo | OFF    | OFF                | ON          | 4             |
| g++-10     | libstdc++ | OFF        | RelWithDebInfo | OFF    | ON                 | ON          | 4             |
| g++-10     | libstdc++ | OFF        | RelWithDebInfo | ON     | OFF                | ON          | 4             |
| g++-10     | libstdc++ | OFF        | RelWithDebInfo | ON     | ON                 | ON          | 4             |
| g++-10     | libstdc++ | ON         | RelWithDebInfo | OFF    | OFF                | ON          | 4             |
| g++-10     | libstdc++ | ON         | RelWithDebInfo | OFF    | ON                 | ON          | 4             |
| g++-10     | libstdc++ | ON         | RelWithDebInfo | ON     | OFF                | ON          | 4             |
| g++-10     | libstdc++ | ON         | RelWithDebInfo | ON     | ON                 | ON          | 4             |
| clang++-18 | libstdc++ | OFF        | Debug          | OFF    | OFF                | ON          | 5             |
| clang++-18 | libstdc++ | OFF        | Debug          | OFF    | ON                 | ON          | 5             |
| clang++-18 | libstdc++ | OFF        | Debug          | ON     | OFF                | ON          | 5             |
| clang++-18 | libstdc++ | OFF        | Debug          | ON     | ON                 | ON          | 5             |
| clang++-18 | libstdc++ | OFF        | RelWithDebInfo | OFF    | OFF                | ON          | 5             |
| clang++-18 | libstdc++ | OFF        | RelWithDebInfo | OFF    | ON                 | ON          | 5             |
| clang++-18 | libstdc++ | OFF        | RelWithDebInfo | ON     | OFF                | ON          | 5             |
| clang++-18 | libstdc++ | OFF        | RelWithDebInfo | ON     | ON                 | ON          | 5             |
```

I haven't yet looked into the clang configurations that are failing.

**Comment by jeremy-rifkin** [comment] 2024-10-06 19:00
Looks like a similar sort of discrepancy on the clang side:

```
0x0000ce68:   DW_TAG_subprogram
                DW_AT_ranges	(indexed (0x3) rangelist = 0x000001fb
                   [0x00000000000246f0, 0x0000000000024da2))
                DW_AT_frame_base	(DW_OP_reg6 RBP)
                DW_AT_linkage_name	("_Z16stacktrace_basicv")
                DW_AT_name	("stacktrace_basic")
                DW_AT_decl_file	(0x01)
                DW_AT_decl_line	(27)
                DW_AT_external	(true)
```
```
CU Name = (indexed string: 0x00000aff)/mnt/c/Users/rifkin/home/projects/cpptrace/test/unit/stacktrace.cpp
CU Producer = (indexed string: 0x00000afe)Ubuntu clang version 18.1.3 (1ubuntu1)
DIE OFF = 0x0000ce68 GOFF = 0x0000ce68, Low PC = 0x00022ec0, High PC = 0x00022fb4
DW_AT_ranges                <index to debug_rnglists 0x00000003> <form DW_FORM_rnglistx 35>
                                      DW_AT_frame_base            len 0x0001: 0x56:  <form DW_FORM_exprloc 24>
                                          DW_OP_reg6
                                      DW_AT_linkage_name          (indexed string: 0x000008f4)_Z16stacktrace_basicv <form DW_FORM_strx2 38>
                                      DW_AT_name                  (indexed string: 0x000008f5)stacktrace_basic <form DW_FORM_strx2 38>
                                      DW_AT_decl_file             0x00000001 <form DW_FORM_data1 11>
                                      DW_AT_decl_line             0x0000001b <form DW_FORM_data1 11>
                                      DW_AT_external              yes(1) <form DW_FORM_flag_present 25>
```

**Comment by davea42** [comment] 2024-10-06 19:46
I assume it is  the DW_AT_ranges values that are in question, but I'm unsure.

I've been trying to build llvm 18 and, so far failing utterly.

**Comment by jeremy-rifkin** [comment] 2024-10-06 19:58
Correct, the differing DW_AT_ranges values seem to be causing errors in stack trace resolution for my library. For llvm dwarfdump, I don't think it's anything special about llvm 18 that's just what I happen to have setup locally. I can check with other versions if it would be helpful.

**Comment by davea42** [comment] 2024-10-06 20:24
So please show me a relevant example of llvm-dwarfdump output for an example part
of  DW_AT_ranges content.   I can see all the relevant parts of the dwo and the tied-file
(independently and together) so I am hoping sone llvm-dwarfdump output  will show such.

**Comment by davea42** [comment] 2024-10-06 20:26
The example you showed above has DW_AT_dwo_id of  3ebed0ea4fd39f55

**Comment by jeremy-rifkin** [comment] 2024-10-06 21:11
I don't seem to have the 3ebed0ea4fd39f55 object around anymore but here's the relevant info for what I sent in the zip archive above which has dwo id 559fd34fead0be3e:

```
unittest:       file format elf64-x86-64

.debug_info contents:
0x00000000: Compile Unit: length = 0x00000030, format = DWARF32, version = 0x0004, abbr_offset = 0x0000, addr_size = 0x08 (next unit at 0x00000034)

...

0x00000073: DW_TAG_compile_unit
              DW_AT_ranges      (0x00061990
                 [0x000000000002a1a0, 0x000000000003006a)
                 [0x000000000000e4e3, 0x000000000000ed32)
                 [0x000000000001ec90, 0x000000000001ec97)
                 ...
                 [0x000000000001a9a0, 0x000000000001a9a9))
              DW_AT_low_pc      (0x0000000000000000)
              DW_AT_stmt_list   (0x0001e44e)
              DW_AT_GNU_dwo_name        ("test/CMakeFiles/unittest.dir/unit/stacktrace.cpp.dwo")
              DW_AT_comp_dir    ("/mnt/c/Users/rifkin/home/projects/cpptrace/build")
              DW_AT_GNU_pubnames        (true)
              DW_AT_GNU_addr_base       (0x000249c8)
              DW_AT_GNU_dwo_id  (0x559fd34fead0be3e)
              DW_AT_GNU_ranges_base     (0x00033b70)
0x0000009c: Compile Unit: length = 0x00000030, format = DWARF32, version = 0x0004, abbr_offset = 0x0057, addr_size = 0x08 (next unit at 0x000000d0)
```

```
test/CMakeFiles/unittest.dir/unit/stacktrace.cpp.dwo:   file format elf64-x86-64

.debug_info.dwo contents:
0x00000000: Compile Unit: length = 0x0009838d, format = DWARF32, version = 0x0004, abbr_offset = 0x0000, addr_size = 0x08 (next unit at 0x00098391)

0x0000000b: DW_TAG_compile_unit
              DW_AT_producer    ("GNU C++17 10.5.0 -mtune=generic -march=x86-64 -g -g -gsplit-dwarf -gdwarf-4 -O2 -std=gnu++2a -fasynchronous-unwind-tables -fstack-protector-strong -fstack-clash-protection -fcf-protection")
              DW_AT_language    (DW_LANG_C_plus_plus)
              DW_AT_name        ("/mnt/c/Users/rifkin/home/projects/cpptrace/test/unit/stacktrace.cpp")
              DW_AT_comp_dir    ("/mnt/c/Users/rifkin/home/projects/cpptrace/build")
              DW_AT_GNU_dwo_id  (0x559fd34fead0be3e)

...

0x0008722c:   DW_TAG_subprogram
                DW_AT_external  (true)
                DW_AT_name      ("stacktrace_basic")
                DW_AT_decl_file (0x07)
                DW_AT_decl_line (27)
                DW_AT_decl_column       (31)
                DW_AT_linkage_name      ("_Z16stacktrace_basicv")
                DW_AT_ranges    (0x00022030
                   [0x000000000002d400, 0x000000000002df68)
                   [0x000000000000e94d, 0x000000000000ea14))
                DW_AT_frame_base        (DW_OP_call_frame_cfa)
                DW_AT_GNU_all_tail_call_sites   (true)
                DW_AT_sibling   (0x0008e081)
```

The relevant part of the ranges section:
```
llvm-dwarfdump-18 unittest --debug-ranges | grep 00022030
00022030 0000000000022044 000000000002205b
00022030 000000000002205b 0000000000022075
00022030 <End of list>
```

**Comment by davea42** [comment] 2024-10-06 21:46
Having looked closely at the CU_DIE and attributes for all three case:

unittest by itself
stacktrace.cpp.dwo by itself
stacktrace.cpp.dwo  with tied unittest

I am not finding anything incorrect or nonsensical.

I  just noticed you have new objects. I don't know
how to access them.  br.zip is the earlier ones.

**Comment by davea42** [comment] 2024-10-07 15:58
"I don't seem to have the 3ebed0ea4fd39f55 object around anymore "

Yes you do, it is in br.zip , link in this issue.

**Comment by davea42** [comment] 2024-10-07 20:00
Since the br.zip has the test object I hope you can provide  the ranges data  from llvm-dwarfdump
that dwarfdump/libdwarf gets wrong.   I just need  to see what llvm does different from dwarfdump
in the case of ranges content.  On a single DIE would be adequate.   With enough
about that DIE so I can recognize it in dwarfdump output.

I suspect I'm not counting a factor in computing a cooked range.

**Comment by jeremy-rifkin** [comment] 2024-10-09 03:12
Hi Dave, thanks for the patience. I've re-done the relevant dumps / analyses as follows with the objects from br.zip. I think I understand the confusion, llvm dwarfdump and dwarfdump from this repository are reporting different dwo ids. Relevant info below:

Dump of just `unittest` by llvm-dwarfdump:

```
0x00000068: Compile Unit: length = 0x00000030, format = DWARF32, version = 0x0004, abbr_offset = 0x003a, addr_size = 0x08 (next unit at 0x0000009c)

0x00000073: DW_TAG_compile_unit
              DW_AT_ranges	(0x00061990
                 [0x000000000002a1a0, 0x000000000003006a)
                 [0x000000000000e4e3, 0x000000000000ed32)
                 ...
                 [0x0000000000000001, 0x0000000000000001)
                 [0x000000000001a9a0, 0x000000000001a9a9))
              DW_AT_low_pc	(0x0000000000000000)
              DW_AT_stmt_list	(0x0001e44e)
              DW_AT_GNU_dwo_name	("test/CMakeFiles/unittest.dir/unit/stacktrace.cpp.dwo")
              DW_AT_comp_dir	("/mnt/c/Users/rifkin/home/projects/cpptrace/build")
              DW_AT_GNU_pubnames	(true)
              DW_AT_GNU_addr_base	(0x000249c8)
              DW_AT_GNU_dwo_id	(0x559fd34fead0be3e)
              DW_AT_GNU_ranges_base	(0x00033b70)
```

Dump of just `unittest` by dwarfdump from this repository:
```
CU_HEADER:
  cu_header_length = 0x00000030 48
  version_stamp    = 0x0004     4
  abbrev_offset    = 0x0000003a 58
  address_size     = 0x08       8
  offset_size      = 0x04       4
  cu_type          = 0x04       DW_UT_skeleton
  signature        = 0x3ebed0ea4fd39f55
  typeoffset       = 0x00000000 0

COMPILE_UNIT<header overall offset = 0x00000068>:
< 0><0x0000000b GOFF=0x00000073>  DW_TAG_compile_unit <abbrev 1 ABGOFF = 0x0000003a count = 0x00000009>
                                    DW_AT_ranges                0x00061990 <form DW_FORM_sec_offset 23>
  ranges: 87 at .debug_ranges offset 399760 (0x00061990)  ( base addr 0x00000000) (1392 bytes)
   [ 0] range entry  raw: 0x0002a1a0,  0x0003006a cooked: 0x0002a1a0,  0x0003006a
   [ 1] range entry  raw: 0x0000e4e3,  0x0000ed32 cooked: 0x0000e4e3,  0x0000ed32
   ...
   [84] range entry  raw: 0x00000001,  0x00000001 (empty range) cooked: 0x00000001,  0x00000001
   [85] range entry  raw: 0x0001a9a0,  0x0001a9a9 cooked: 0x0001a9a0,  0x0001a9a9
   [86] range end    0,0
                                    DW_AT_low_pc                0x00000000 <form DW_FORM_addr 1>
                                    DW_AT_stmt_list             0x0001e44e <form DW_FORM_sec_offset 23>
                                    DW_AT_GNU_dwo_name          test/CMakeFiles/unittest.dir/unit/stacktrace.cpp.dwo <form DW_FORM_strp 14>
                                    DW_AT_comp_dir              /mnt/c/Users/rifkin/home/projects/cpptrace/build <form DW_FORM_strp 14>
                                    DW_AT_GNU_pubnames          yes(1) <form DW_FORM_flag_present 25>
                                    DW_AT_GNU_addr_base         0x000249c8 <form DW_FORM_sec_offset 23>
                                    DW_AT_GNU_dwo_id            0x3ebed0ea4fd39f55 <form DW_FORM_data8 7>
                                    DW_AT_GNU_ranges_base       0x00033b70 <form DW_FORM_sec_offset 23>
```

Dump of header/CU info from `stacktrace.cpp.dwo` as well as the DIE I'm looking at by llvm dwarfdump (llvm-dwarfdump doesn't have a `--file-tied=file` like yours, only a `--dwo` flag requiring the dwo to be in the correct absolute path, but I can get the relevant info):

```
0x0000000b: DW_TAG_compile_unit
              DW_AT_producer	("GNU C++17 10.5.0 -mtune=generic -march=x86-64 -g -g -gsplit-dwarf -gdwarf-4 -O2 -std=gnu++2a -fasynchronous-unwind-tables -fstack-protector-strong -fstack-clash-protection -fcf-protection")
              DW_AT_language	(DW_LANG_C_plus_plus)
              DW_AT_name	("/mnt/c/Users/rifkin/home/projects/cpptrace/test/unit/stacktrace.cpp")
              DW_AT_comp_dir	("/mnt/c/Users/rifkin/home/projects/cpptrace/build")
              DW_AT_GNU_dwo_id	(0x559fd34fead0be3e)

0x0008722c:   DW_TAG_subprogram
                DW_AT_external	(true)
                DW_AT_name	("stacktrace_basic")
                DW_AT_decl_file	(0x07)
                DW_AT_decl_line	(27)
                DW_AT_decl_column	(31)
                DW_AT_linkage_name	("_Z16stacktrace_basicv")
                DW_AT_ranges	(0x00022030
                   [0x000000000002d400, 0x000000000002df68)
                   [0x000000000000e94d, 0x000000000000ea14))
                DW_AT_frame_base	(DW_OP_call_frame_cfa)
                DW_AT_GNU_all_tail_call_sites	(true)
                DW_AT_sibling	(0x0008e081)
```

Dump of header/CU info from `stacktrace.cpp.dwo` as well as the DIE I'm looking at by dwarfdump from this repository:
```
CU_HEADER:
  cu_header_length = 0x0009838d 623501
  version_stamp    = 0x0004     4
  abbrev_offset    = 0x00000000 0
  address_size     = 0x08       8
  offset_size      = 0x04       4
  cu_type          = 0x05       DW_UT_split_compile
  signature        = 0x3ebed0ea4fd39f55
  typeoffset       = 0x00000000 0

COMPILE_UNIT<header overall offset = 0x00000000>:
< 0><0x0000000b GOFF=0x0000000b>  DW_TAG_compile_unit <abbrev 304 ABGOFF = 0x0000175c count = 0x00000005>
                                    DW_AT_producer              (indexed string: 0x000021f3)GNU C++17 10.5.0 -mtune=generic -march=x86-64 -g -g -gsplit-dwarf -gdwarf-4 -O2 -std=gnu++2a -fasynchronous-unwind-tables -fstack-protector-strong -fstack-clash-protection -fcf-protection <form DW_FORM_GNU_str_index 7938>
                                    DW_AT_language              DW_LANG_C_plus_plus <form DW_FORM_data1 11>
                                    DW_AT_name                  (indexed string: 0x000003df)/mnt/c/Users/rifkin/home/projects/cpptrace/test/unit/stacktrace.cpp <form DW_FORM_GNU_str_index 7938>
                                    DW_AT_comp_dir              (indexed string: 0x000006dc)/mnt/c/Users/rifkin/home/projects/cpptrace/build <form DW_FORM_GNU_str_index 7938>
                                    DW_AT_GNU_dwo_id            0x3ebed0ea4fd39f55 <form DW_FORM_data8 7>

< 1><0x0008722c GOFF=0x0008722c>    DW_TAG_subprogram <abbrev 399 ABGOFF = 0x00001eeb count = 0x0000000a>
                                      DW_AT_external              yes(1) <form DW_FORM_flag_present 25>
                                      DW_AT_name                  (indexed string: 0x000013ef)stacktrace_basic <form DW_FORM_GNU_str_index 7938>
                                      DW_AT_decl_file             0x00000007 <form DW_FORM_data1 11>
                                      DW_AT_decl_line             0x0000001b <form DW_FORM_data1 11>
                                      DW_AT_decl_column           0x0000001f <form DW_FORM_data1 11>
                                      DW_AT_linkage_name          (indexed string: 0x000008be)_Z16stacktrace_basicv <form DW_FORM_GNU_str_index 7938>
                                      DW_AT_ranges                0x00022030 <form DW_FORM_sec_offset 23>
  ranges: 3 at .debug_ranges offset 139312 (0x00022030)  ( base addr 0x00000000) (48 bytes)
   [ 0] range entry  raw: 0x00022044,  0x0002205b cooked: 0x00022044,  0x0002205b
   [ 1] range entry  raw: 0x0002205b,  0x00022075 cooked: 0x0002205b,  0x00022075
   [ 2] range end    0,0
                                      DW_AT_frame_base            len 0x0001: 0x9c:  <form DW_FORM_exprloc 24>
                                          DW_OP_call_frame_cfa
                                      DW_AT_GNU_all_tail_call_sites yes(1) <form DW_FORM_flag_present 25>
                                      DW_AT_sibling               <0x0008e081 GOFF=0x0008e081> <form DW_FORM_ref4 19>
```


Exact steps I performed (mainly for my own memory)
```
unzip br.zip
cd br
llvm-dwarfdump-18 unittest > unittest-llvm-dump.txt
dwarfdump -i -M -G  -vv unittest > unittest-libdwarf-dump.txt
mkdir -p /mnt/c/Users/rifkin/home/projects/cpptrace/build/test/CMakeFiles/unittest.dir/unit
cp test/CMakeFiles/unittest.dir/unit/stacktrace.cpp.dwo /mnt/c/Users/rifkin/home/projects/cpptrace/build/test/CMakeFiles/unittest.dir/unit
llvm-dwarfdump-18 unittest --dwo > stacktrace-llvm-dump.txt
dwarfdump -i -M -G  -vv --file-tied=unittest test/CMakeFiles/unittest.dir/unit/stacktrace.cpp.dwo > stacktrace-libdwarf-dump.txt
```

**Comment by davea42** [comment] 2024-10-09 23:25
Well, something odd above I am puzzled about.
I added some debug to libdwarf and on the unittest or the stacktrace.cpp.dwo  from br.zip
so I would be sure to see all  signature reads and assigns  in libdwarf.
I cannot find any  dwo_id of   0x559fd34fead0be3e as you show from llvm-dwarfdump ... anywhere.

All I find is
```
junkdwo:dadebug attrname is DW_AT_GNU_dwo_id
junkdwo:dadebug DW_AT_..   0x3ebed0ea4fd39f55 line 1423
junkdwot:dadebug attrname is DW_AT_GNU_dwo_id
junkdwot:dadebug DW_AT_..   0x3ebed0ea4fd39f55 line 1423
junkdwot:dadebug attrname is DW_AT_GNU_dwo_id
junkdwot:dadebug DW_AT_..   0xeba3efaf51f6ddf1 line 1423
junkdwot:dadebug attrname is DW_AT_GNU_dwo_id
junkdwot:dadebug DW_AT_..   0xe80f6ea416149751 line 1423
junkdwot:dadebug attrname is DW_AT_GNU_dwo_id
junkdwot:dadebug DW_AT_..   0x3ebed0ea4fd39f55 line 1423
junkexe:dadebug attrname is DW_AT_GNU_dwo_id
junkexe:dadebug DW_AT_..   0xeba3efaf51f6ddf1 line 1423
junkexe:dadebug attrname is DW_AT_GNU_dwo_id
junkexe:dadebug DW_AT_..   0xe80f6ea416149751 line 1423
junkexe:dadebug attrname is DW_AT_GNU_dwo_id
junkexe:dadebug DW_AT_..   0x3ebed0ea4fd39f55 line 1423
junkexe:dadebug attrname is DW_AT_GNU_dwo_id
junkexe:dadebug DW_AT_..   0x2454b5c4dc369c8a line 1423
junkexe:dadebug attrname is DW_AT_GNU_dwo_id
junkexe:dadebug DW_AT_..   0x7b7c5ce3c029c83b line 1423
junkexe:dadebug attrname is DW_AT_GNU_dwo_id
junkexe:dadebug DW_AT_..   0xbbf123e6a4ecd9cc line 1423

```

**Comment by jeremy-rifkin** [comment] 2024-10-10 01:38
I think it's just an endianness issue, `559fd34fead0be3e` is `3ebed0ea4fd39f55` byteswapped.

**Comment by davea42** [comment] 2024-10-10 22:38
It seems that

https://gardinal.net/forums/topic/how-to-build-llvm-on-linux/

does have some usable llvm build instructions.

**Comment by davea42** [comment] 2024-10-11 15:50
While the full build failed on a C++ error message
the llvm-dwarfdump Makefile got created, so in that build directory
a 'make' seemed to work.  I have an executable llvm-dwarfdump.

However I do not get the output you do, and  the --dwo option is not named in the --help output,


I can get 
```
0x0008722c:   DW_TAG_subprogram
                DW_AT_external  (true)
                DW_AT_name  ("stacktrace_basic")
                DW_AT_decl_file (0x07)
                DW_AT_decl_line (27)
                DW_AT_decl_column   (31)
                DW_AT_linkage_name  ("_Z16stacktrace_basicv")
                DW_AT_ranges    (0x00022030)
                DW_AT_frame_base    (DW_OP_call_frame_cfa)
                DW_AT_GNU_all_tail_call_sites   (true)
                DW_AT_sibling   (0x0008e081)
```

but notice no words about the ranges content here.

**Comment by davea42** [comment] 2024-10-11 20:39
So, in the top-of-trunk (latest) build shown on gardinal,
It fails for me  in  SPIRV-LLVM-Translator/lib/SPIRV/SPIRVReader.cpp.

So then do (again in build directory):
make llvm-dwarfdump

and it successfully creates llvm-dwarfdump and places in in build/bin

**Comment by davea42** [comment] 2024-10-11 21:01
Running the following:
```
ll=/home/downloads/llvmclone/llvm/build/bin/llvm-dwarfdump
$ll unittest >junkllexe
$ll --dwo test/CMakeFiles/unittest.dir/unit/stacktrace.cpp.dwo >junklldwo
$ll --dwo  unittest >junklldwot


```
But llvm-dwarfdump is not expanding DW_AT_ranges.

```
q3 785: ls -l junkll*
-rw-rw-r-- 1 davea davea  19266223 Oct 11 13:44 junklldwo
-rw-rw-r-- 1 davea davea 154905394 Oct 11 13:44 junklldwot
-rw-rw-r-- 1 davea davea 154905394 Oct 11 13:44 junkllexe
```
Does not seem to matter where I place the --dwo.

What am I doing wrong?

```
0x0008722c:   DW_TAG_subprogram 
                DW_AT_external  (true)
                DW_AT_name  ("stacktrace_basic")
                DW_AT_decl_file (0x07)
                DW_AT_decl_line (27)
                DW_AT_decl_column   (31)
                DW_AT_linkage_name  ("_Z16stacktrace_basicv")
                DW_AT_ranges    (0x00022030)
                DW_AT_frame_base    (DW_OP_call_frame_cfa)
                DW_AT_GNU_all_tail_call_sites   (true)
                DW_AT_sibling   (0x0008e081)

```

**Comment by davea42** [comment] 2024-10-15 15:57
Major computer failure here. Do NOT expect Ubuntu 24.04.1 LTS to work. Be warned.
It broke 2 machines Upgrading from 22.04 LTS.  

And my major desktop had graphics fail too. Been 3 days on this and don't expect to be
fully back in operation for 10 days at least. Ordered one new desktop and recovering
via reinstall the working one of the pair.

**Comment by jeremy-rifkin** [comment] 2024-10-28 02:28
Sorry to hear you've ran into ubuntu issues, I hate it when that happens.

Regarding llvm-dwarfdump not expanding DW_AT_ranges, unfortunately llvm-dwarfdump needs the files at exact absolute paths. The dwo on my system was at `/mnt/c/Users/rifkin/home/projects/cpptrace/build/test/CMakeFiles/unittest.dir/unit/test/CMakeFiles/unittest.dir/unit/stacktrace.cpp.dwo`. If it's easy to just cp the file over, that would probably be fastest. Otherwise I can send instructions to build an artifact that will work on your computer.

**Comment by davea42** [comment] 2024-10-28 14:46
Absolute path. Had not occurred to me.
Yes I can put the dwo file at such a path here.  Hopefully today.?

**Comment by davea42** [comment] 2024-10-30 16:42
I put the dwo at the right place under mnt and now
llvm-dwarfdump gets the values you reported for DW_AT_ranges on stacktrace_basic.

Using the llvm-dwarfdump I built myself here. So this is progress.

**Comment by davea42** [comment] 2024-10-31 21:28
The llvm-dwarfdump I build myself, doing
`/tmp/llvm-dwarfdump  -v  unittest -dwo`

gets numerous 'decoding error'.

And its attempt to follow DW_AT_ranges fails in may cases with that error.
It also is not 100% consistent in output.

Whereas dwarfdump finds no errors.

Please check with your llvm-dwarfdump  in DWARF4.
Does it get decoding errors?

I find no reason to trust llvm-dwarfdump.

**Comment by davea42** [comment] 2024-10-31 21:42
An example from llvm-dwarfdump

```
0x00037a23:                             DW_TAG_formal_parameter [1]   (0x000379f5)
                                          DW_AT_abstract_origin [DW_FORM_ref4]  (cu + 0x43e5e => {0x00043e5e} "__capacity")
                                          DW_AT_location [DW_FORM_sec_offset]   (0x00000b14:
                                             [0x0000000000025cd6, 0x0000000000025d00): <decoding error> f2 00 00 00 00 00
                                             [0x0000000000025d0a, 0x0000000000025d1b): <decoding error> f2 00 00 00 00 00)
                                          DW_AT_GNU_locviews [DW_FORM_sec_offset]       (0x00000b10)

```
Something very odd here.

**Comment by davea42** [comment] 2024-10-31 21:51
The message seems to come from only DwarfExpression.cpp in llvm/llvm/lib/DebugInfo/DWARF

 ```
302 bool DWARFExpression::Operation::print(raw_ostream &OS, DIDumpOptions DumpOpts,
    303                                        const DWARFExpression *Expr,
    304                                        DWARFUnit *U) const {
    305   if (Error) {
    306     OS << "<decoding error>";
    307     return false;
    308   }

```

but  my understanding of this C++ source is ...minimal... as I've not looked at it before.

**Comment by davea42** [comment] 2024-11-02 21:57
I know finally realize that in the very first DW_AT_ranges output
dwarfdump and llvm-dwafdump are doing very different output.
Even the length of the rangelist differs.  Aha.

**Comment by davea42** [comment] 2024-11-03 00:05
The problem was that for DWARF4 split-dwarf gcc was using DW_AT_entry_pc to inform the library
that such was to be interpreted as the base_address  for ranges etc.

While we've kind of allowed that (for Apple compilers) a tiny change in libdwarf was needed
in the pre-scan of each compilation unit.

```
-    } else if (entry_pc_attrnum >= 0) {
+    } 
+    if (entry_pc_attrnum >= 0) {
         int battr = 0;

in  _dwarf_setup_base_address().

I am running full regressionests now.
```

**Comment by davea42** [comment] 2024-11-04 17:06
llvm-dwarfdump:
```
DW_AT_abstract_origin (0x0005fc1e "_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc")
                  DW_AT_entry_pc        (0x000000000002585e)
                  DW_AT_GNU_entry_view  (0x0002)
                  DW_AT_ranges  (0x00001510
                     [0x000000000002585e, 0x000000000002585e)
                     [0x000000000002585e, 0x0000000000025876))
                  DW_AT_call_file       (0x02)
                  DW_AT_call_line       (251)
```
dwarfdump just built


Notice the number of ranges printed. 
```
< 2><0x00036e4a GOFF=0x00036e4a>      DW_TAG_inlined_subroutine <abbrev 8 ABGOFF = 0x0000005e count = 0x00000008>
                                        DW_AT_abstract_origin       <0x0005fc1e GOFF=0x0005fc1e>
                                        DW_AT_entry_pc              (addr_index: 0x000019b5)0x0002585e
                                        DW_AT_GNU_entry_view        2
                                        DW_AT_ranges                0x00001510
  ranges: 4 at .debug_ranges offset 5392 (0x00001510)  ( base addr 0x0002585e) (64 bytes)
   [ 0] range entry  raw: 0x0001c471,  0x0001c481 cooked: 0x00041ccf,  0x00041cdf
   [ 1] range entry  raw: 0x0001c485,  0x0001c492 cooked: 0x00041ce3,  0x00041cf0
   [ 2] range entry  raw: 0x0001c638,  0x0001c648 cooked: 0x00041e96,  0x00041ea6
   [ 3] range end    0,0
                                        DW_AT_call_file             0x00000002
                                        DW_AT_call_line             0x000000fb
                                        DW_AT_call_column           0x00000005
                                        DW_AT_sibling               <0x00036e71 GOFF=0x00036e71>
```

I know from a simple scan of .debug_ranges that dwarfdump prints the contents of the section
correctly and the .debug_ranges at 0x1510  is indeed three entries followed by 0,0 end of range list.

I am unsure about a lot of things, but not the count of items in the ranges list for 0x1510.

So my version of llmv-dwarfdump is definitely broken. Please try yours and let me know what it shows
for this particular function.

**Comment by davea42** [comment] 2024-11-04 17:10
And here is this ranges group from .debug_ranges as it is in the object file:
```
Ranges group 90:
  ranges: 4 at .debug_ranges offset 5392 (0x00001510) (64 bytes)
   [ 0] range entry  raw: 0x0001c471,  0x0001c481
   [ 1] range entry  raw: 0x0001c485,  0x0001c492
   [ 2] range entry  raw: 0x0001c638,  0x0001c648
   [ 3] range end    0,0

```
The Ranges group here is just a running count of the lists, this is the 90th such in .debug_ranges.

**Comment by davea42** [comment] 2024-11-05 21:40
I've conducted a review of standard split-dwarf (DWARF5) and that revealed
a mistake in GNU-extension DWARF4 split dwarf (for DW_AT_ranges and loclists). work in progress.

**Comment by jeremy-rifkin** [comment] 2024-11-08 16:49
Hi Dave, thank you so much for looking into this working on a fix! Sorry this has been a bit of a hassle with llvm dwarfdump. It sounds reasonable to me that this was a issue with DW_AT_entry_pc / base addresses. When this is fixed I can run my library unit tests with this new version and report back.

**Comment by davea42** [comment] 2024-11-09 00:21
The problem is an accidental oversight on my part. 
I forgot to merge the  DW_AT_GNU_ranges_base
(and DW_AT_ranges_base)  from the skeleton into the split-full CU.

I have major testing to do.

**Comment by davea42** [comment] 2024-11-09 18:06
Regression testing demonstrates (by showing appropriate
differences) that I already have a DWARF4 test involving DWARF4 split-dwarf
so do not need your example of unittest.  
But without your Issue here I would not have known there was a problem.
So a very big thank you.

**Comment by jeremy-rifkin** [comment] 2024-11-10 00:09
Awesome and thank you for all the work on your end!

**Comment by jeremy-rifkin** [comment] 2024-11-10 05:07
Would it be helpful to set up some automated testing of libdwarf e.g with github actions? I'm not sure what your test setup is like but I'd be happy to contribute and set something up if you would be interested.

**Comment by davea42** [comment] 2024-11-10 16:05
Pushed the fixes (including improvements to the clarity of dwarfdump output)
so closing this.

**Closed by davea42** 2024-11-10 16:05 UTC

**Comment by jeremy-rifkin** [comment] 2024-11-10 18:45
Thank you, I confirmed my library's gcc 10 dwarf 4 split-dwarf test cases now pass
